### ISSUE TITLE
`{{ search_snippets }}` does not return anything since v5

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/cms#10251]
### Bug description

I did an update to v5 and it is not returning anything since then.
`4.58.2`
<img width="753" alt="Bildschirmfoto 2024-06-03 um 11 38 13" src="https://github.com/statamic/cms/assets/6337411/3d3dc7d2-91c4-4626-b8df-fe94523d5eb9">

`5.6.2`
<img width="554" alt="Bildschirmfoto 2024-06-03 um 11 38 22" src="https://github.com/statamic/cms/assets/6337411/13d4d9c6-462d-4310-9950-f44e2010aa45">

### How to reproduce

- create project with 4.x
- create output with `{{ search_snippets }}`
- update to v5
- check output of search

### Environment

```yaml
Statamic: 5.6.2 Solo
```

### Installation

Other (please explain)

### Additional details

Cloned 4.x and 5.x from https://github.com/statamic/statamic.

**Comment by duncanmcclean** [comment]
Can you please provide the full output of `php please support:details`?

**Comment by j3ll3yfi5h** [comment]
@duncanmcclean sure:

```
Environment
Application Name: Statamic
Laravel Version: 11.9.2
PHP Version: 8.2.14
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: null
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.6.2 Solo
```

**Comment by duncanmcclean** [comment]
Thanks!

To future self, or whoever ends up tackling this, it seems that the `result_type`/`search_score`/`search_snippets` variables added here aren't included when you `{{ dump }}` inside the results tag:

![CleanShot 2024-06-05 at 15 22 39](https://github.com/statamic/cms/assets/19637309/520236fb-c309-424c-b8f3-62843892c49e)

However, the variables *are* present when the search tag [returns the results](https://github.com/statamic/cms/blob/6f8c4c29e256c865f2a56b5f700e237fddcd4545/src/Search/Tags.php#L43), which makes me think it's being filtered out when the result is augmented (possibly caused by some of our caching changes in v5).

**Comment by jasonvarga** [comment]
Bump
