### ISSUE TITLE
View [components.heading] not found.

### ISSUE THREAD

**Issue by dcrebelio** [statamic/cms#10803]
### Bug description

I was migrating a blog from wodrpess, to statamic and I have my local project, and after a few days off the project I get the following error, ONLY when trying to access the admin panel.

![Screenshot from 2024-09-16 09-27-35](https://github.com/user-attachments/assets/a8d7d99c-c2bf-4161-b414-a15161c35d76)

### How to reproduce

This is the statamic version of 
```
"name": "statamic/cms",
            "version": "v5.20.0",
```

### Logs

```shell
https://flareapp.io/share/NPGQJOk5
```

### Environment

```yaml
I'm using laravel sail to run de local enviorement.
```

### Installation

Starter Kit using via CLI

### Additional details

I'm using the starter kit, statamic-peak

**Comment by duncanmcclean** [comment]
I don't think this is a Statamic issue, we don't reference a `components.heading` partial anywhere in our code.

Can you do a "find in all files" and see where you're referencing it? Maybe it's being references somewhere and you've deleted it.

You're also accessing `/admin`, is this intentional? By default, the CP is accessible at `/cp`.
