### ISSUE TITLE
Typing in the content editor feels laggy while using Safari

### ISSUE THREAD

**Issue by owenconti** [statamic/cms#1171]
While using Safari, typing in the content editor feels laggy (delayed response while typing). While using Chrome on the same machine, the content editor doesn't feel laggy.

Specs:

Safari 13.0.4
Running OSX 10.15.2
MacBook Pro (13-inch, 2019, Two Thunderbolt 3 ports)
Processor: 1.4 GHz Quad-Core Intel Core i5
Memory: 16 GB 2133 MHz LPDDR3

**Comment by jackmcdade** [comment]
Which fieldtype? Bard? Markdown?

**Comment by edalzell** [comment]
Bard & Markdown both exhibit this for me.

**Comment by owenconti** [comment]
Sorry Jack, I've experienced it in Bard and Text so far. I tried to find an easily way to capture it to show what I mean, but it's hard to capture a feeling. Here's the best I could do:

* I took a screen recording of myself typing "One two three" (I made a typo so it ended up as "One two tthree")
* I then took a second screen recording as I scrubbed through the first recording one frame at a time

![statamic-laggy-typing 2020-01-04 19_04_33](https://user-images.githubusercontent.com/791222/71774053-1ae91600-2f25-11ea-9050-5cf57ddf2f10.gif)

* So the first 5 characters are fine: "One t"
* Then instead of getting a frame for "w" and another for "o", we got a bit of a delay and then both "wo" appear together in the next frame
* The next characters " t" go through fine
* Then I make the typo, but the lag happens again for characters "th" where they both appear in the same frame.

Hopefully that helps!

**Comment by derekjones** [comment]
FWIW I don't seem to experience this. macOS Catalina 10.15.2. Have you tried disabling browser extensions? Some are very aggressive with forms and can do odd things—LastPass comes to mind.

**Comment by jasonvarga** [comment]
Yeah I was just about to ask, do you have any extensions enabled?

**Comment by edalzell** [comment]
I do, I'll disable and re-test

**Comment by owenconti** [comment]
I only had 1Password installed. Disabled it and still experienced it. Worth noting that on a more powerful machine, it doesn't seem to be as noticeable.

**Comment by edalzell** [comment]
and I'm on an underpowered 2017 MacBook

**Comment by edalzell** [comment]
I disabled all my extensions and it is still laggy for me.

**Comment by jasonvarga** [comment]
Do you have devtools open? Is it any better with them closed?

**Comment by edalzell** [comment]
I do not have dev tools open. No lag in Firefox.

**Comment by jackmcdade** [comment]
I wasn't able to recreate this but removed the `eqcss` query that was applied to each fieldtype. There only a few very minor calls to it now, so hopefully no longer an issue.

371e5e22ddac1d5bc236012c25e644a614199d52

If someone can confirm when beta20 is out I would appreciate it!

**Comment by jackmcdade** [comment]
@JonKaric how were you able to determine it was `eqcss.throttle` on input that was causing the reflow?

**Comment by JonKaric** [comment]
It was EQCSS causing the reflow, can't confirm it was `eqcss.throttle` but that was the root of the janky-ness for me. Happens when you interact with the page too, but it's not as bad.

Chrome dev tools > Performance > Record the page / whilst typing > Open the `main` tab

**Comment by tao** [comment]
I'm experiencing this problem too. I'm using a very long document and there's like a ~1 to 2 second lag after each key press, so it's not really usable at the moment.

**Comment by JonKaric** [comment]
@jackmcdade This still happens on the latest beta, `3.0.0-beta.27`. I found [this](https://github.com/eqcss/eqcss/wiki/Understanding-EQCSS-Triggers) page to be really useful. 

If you're only using it to control the width of the `.publish-field`(s) based on the parent width, then you can do away with everything except the resize listener because that's the only one that will affect the widths of the fields.

The fields have set widths anyway, so typing content (listening for `input`) is redundant. The same with `mousedown`, `mouseup`, `mousemove`. You may need `click` somewhere for stacks™ or something? I'm not sure.

**Comment by AlexanderLindkjaer** [comment]
@jackmcdade We are severely affected by this problem to. Big input lag on everything from bard editor, toogles, selects and so on. 

Only happens when the blueprints require a lot input fields. Happens on all tested browsers and devices.

here is a gif of it, where only on whole word is appearing at a time due to lag :) 

![Screen Recording 2020-06-12 at 3 53 29 PM](https://user-images.githubusercontent.com/33224052/84510313-438bed80-acc5-11ea-937b-a3f24ebc652f.gif)

**Comment by jasonvarga** [comment]
This may be related to #1915

**Comment by jasonvarga** [comment]
@JonKaric Thanks for that link. Do you actually see a way to disable certain events?

Locally I've brought eqcss inline and simply commented out the `input` event binding. It seems to help quite a bit. It would be nice if there was a setting I could use instead of having to "fork" the project.
