### ISSUE TITLE
After the last update validations are gone

### ISSUE THREAD

**Issue by lightbringer93** [statamic/cms#1197]
![Screenshot 2](https://user-images.githubusercontent.com/27002677/72220063-310e5c00-354d-11ea-8f01-e9f9d7d1308c.png)
After updating from v3.0.0-beta.8 to v3.0.0-beta.9 my validations disappeared. I can not create any new validations and can not see any I already created.

**Comment by damcclean** [comment]
I'm experiencing exactly the same issue too. Thought it was just one of my fields but they all seem to be affected by this.

**Comment by damcclean** [comment]
Looks like it's down to a bad bit of regexing😂

Line 61 in `field-validation/Builder.vue` has this code:
`let version = new RegExp('([0-9]+\.[0-9])\.[0-9]+').exec(this.laravelVersion)[1];`

Although, the regex rules will error out if the Laravel version is something like `6.10.*` because it can't parse version parts over 9.

Was going to have a go at fixing this but I'm rubbish at regex.

**Comment by WebsiteDeveloper** [comment]
Just adding a 1 or more quantifier should be fine smth like this ([0-9]+\.[0-9]+)\.[0-9]+
Il add a PR
