### ISSUE TITLE
Laravel/DB Users: Action unauthorized for most CP routes

### ISSUE THREAD

**Issue by 1stevengrant** [statamic/cms#1266]
I've installed Statamic into an existing Laravel app and storing users in the db.

The created user has been assigned as a superuser but if I try to visit `fields` or `collections` (and others), I get the unauthorized toast notification.

**Comment by dan-mesa** [comment]
I'm out of my depth here but as far as I can tell, the issue is somewhere in the vicinity of `Providers/AuthServiceProvider.php`, specifically the `boot` method finds `$user` to not be an instance of `StatamicUser` only when storing users in the database:

```
if ($user instanceof StatamicUser) {
    return User::fromUser($user)->isSuper() ? true : null;
}
```

The result, of course, is the `$this->authorize(...)` calls in `StructuresController.php` fail, prompting the saddest toast I've ever not eaten.

I assume some minor tweaking of `Contracts/Auth/User.php` would fix this but I don't know enough about interfaces to take it any further.

**Comment by theblacksheepltd** [comment]
Not sure if this helps with troubleshooting, but I was able to get access to most CP areas by creating a role called "admin" with all available access options, then manually creating the relationship in the db "role_user" field. Doesn't allow access to Fields, Groups, or Roles, but can now access other CP areas.

**Comment by jasonvarga** [comment]
Thanks for this, I see this issue was introduced in #1228. We'll think of another solution. 👌

**Comment by theblacksheepltd** [comment]
If I run an update should this be working now? I'm still getting the same
errors, but if it's still pending a fix that's fine...

Thanks,


*Brian Shepherd*
——————————
*Black Sheep Design Ltd.*
720.201.9764
theblacksheepltd.com

**Comment by jasonvarga** [comment]
It'll be available when the next release is tagged (beta 15).

**Comment by theblacksheepltd** [comment]
Great - thanks!


*Brian Shepherd*
——————————
*Black Sheep Design Ltd.*
720.201.9764
theblacksheepltd.com
