### ISSUE TITLE
When you delete one favorite, all favorites are deleted

### ISSUE THREAD

**Issue by WiebkeVog** [statamic/cms#1270]
All favorites are deleted from the user's preferences if we only want to delete one.
This behaviour could be reproduced by deleting via search and by clicking on the "Unpin from Favorites" icon.

**Comment by jackmcdade** [comment]
Confirmed. Thanks for the report!

**Comment by jesseleite** [comment]
Hey @jasonvarga this was a regression because of https://github.com/statamic/cms/issues/894.  That revert fixes the issue, but I'm sure there was a reason for https://github.com/statamic/cms/commit/a3a4077cbd86087904fcbae32c8de435b3bd172a; I'm confused why we can't use a DELETE route in this circumstance?

**Comment by jasonvarga** [comment]
Delete routes cannot have payloads.

Usually it’s fine but on some stricter servers it’s not supported.

**Comment by jesseleite** [comment]
Ah okay 👍  I guess it's a greyer area, because the spec doesn't specifically disallow it.
