### ISSUE TITLE
Add a mount var to entries

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#1352]
In v3 the mount is made on the collection side instead of entry.
A side effect of this is the mount variable disappeared in templates.

Make it so.

**Comment by Pixney-William** [comment]
I am guessing my issue is what you have added above. However, since I am not 100% sure i thought I would just add what I experience:

When I add `mount: e488dad3-c168-4fd9-8061-7a00649969d6` in a collection YAML field (since there is no mount field in the UI) everything works as expected. 

But it is removed, if I go into **Edit Collection** and makes a change.
