### ISSUE TITLE
In a fresh v3 installation, I can't edit a fieldset after creating it!

### ISSUE THREAD

**Issue by peimann** [statamic/cms#1410]
Create a fieldset and get bak to fieldsets page then click on the fieldset.
![image](https://user-images.githubusercontent.com/40042952/74845146-ce766000-5343-11ea-9203-02d271d8c297.png)

Notice: I have followed the instructions on docs how to install v3.

**Comment by jackmcdade** [comment]
I can't recreate this. Are you on beta 17? If so, what other things have done since installing it fresh?

Also, and related but not the same point (there very well may be a bug) – are you sure you want a Fieldset? Blueprints are the **primary** think you make in v3 - Fieldsets are just for creating reusuable groups of fields that you import into your blueprints.

**Comment by riasvdv** [comment]
This is fixed here https://github.com/statamic/cms/commit/2659fd1c5e3c2626ff36cb1d381dccd2e4d3bd33 but not released yet

**Comment by peimann** [comment]
@jackmcdade yeah I know, I am already familiar with blueprints and fieldsets.
Nothing have done, just create fieldset and then tried to edit that.

**Comment by peimann** [comment]
@riasvdv yup, seams the same issue...

**Comment by jasonvarga** [comment]
It's fixed but not tagged yet.
