### ISSUE TITLE
[content API] Bard always returns HTML

### ISSUE THREAD

**Issue by igregson** [statamic/cms#1417]
The content API is always returning Bard field values as HTML, even when the field's "Save HTML" setting in the blueprint is set to `false`.

**Comment by jasonvarga** [comment]
The save as html option is for when you don't have any sets and just want to literally save an html string instead of the prosemirror structure.

If you don't have any sets configured, you will get HTML back from the API (and in your templates) regardless of that setting. We never expect to you to have to manually convert prosemirror's structure into html by hand.

Does your field have any `sets` ?

**Comment by igregson** [comment]
Ah, I see. That makes sense. I had interpreted it to be: `save-as-html = false` and the API would return the raw structure (with no serialized HTML, essentially a 1-to-1 for what's saved in the content file).

Yes, my field had sets, though I tested with and without to fully understand how they change the API's return value here (in relation to the "Save as HTML" toggle).

Seems this is working as intended. Will close.

Thank you!
