### ISSUE TITLE
Blade templates have some developer issues

### ISSUE THREAD

**Issue by riasvdv** [statamic/cms#1446]
This makes sure modifiers can always deal with expected strings or arrays

- [ ] Call ->value() on Value Objects inside Modify::value()
- [ ] There's no global `modify()` helper yet
- [ ] Implement `ArrayAccess` in Value Objects

**Comment by damcclean** [comment]
For note of anyone who finds this issue: there's some discussion about this in #2717 and #2724.

**Comment by damcclean** [comment]
Keep this open, blade with Statamic isn't the best.

**Comment by jacksleight** [comment]
I have one to add to this:

When passing a value to a blade component all props/attributes are passed through in the component data, and also into the attribute bag object. When objects are added to the attribute bag they're automatically cast to strings if they contain a `__toString()` method.

`Statamic\Fields\Value` has a `__toString()` method, however for Bard values with sets this method errors (unable to convert array to a string).

This makes it impossible to pass Bard values with sets to blade components without a workaround. Im currently wrapping those values in an array so blade does not attempt to cast it to a string.

```
<x-component :content="[$content]" />
```

**Comment by jasonvarga** [comment]
@jacksleight Your comment is addressed in #5201 - see the last section "String/JSON Casting".

**Comment by jasonvarga** [comment]
As for the original 3 items in this issue:

> There's no global modify() helper yet

It's still not a global, but it's shorter. As of #5058 you can do `{{ Statamic::modify($value) }}`

> Call ->value() on Value Objects inside Modify::value()

There will be no need to do that anymore in #5201. If you do `$page->myvalue` instead of just `{{ $myvalue }}`, you don't need to call `->value()`.

`{{ Statamic:modify($page->myvalue)->whatever() }}` will work.

> Implement ArrayAccess in Value Objects

Again, won't be necessary since #5201 you won't be dealing with `Value` objects at all anymore.
