### ISSUE TITLE
Ability to switch blueprints

### ISSUE THREAD

**Issue by steveooo1** [statamic/cms#1460]
I want to use a `blueprint` named Blueprint field, so I am able to switch between blueprints via "select new blueprint", save, see the fields of the new blueprint.

This does not work, because it throws a message like "is an array" below the field and it could not save the changed field value.

Using the latest and greatest beta.

**Comment by steveooo1** [comment]
@jackmcdade Any update on this?

**Comment by jackmcdade** [comment]
It was never intended to be used as a publish field, it was only supposed to be used elsewhere like in the collection/taxonomy/form config forms. Switching between blueprints would be pretty problematic and might result in losing data and other things...

**Comment by steveooo1** [comment]
Okay. If someone needs to have different types of content with different fields per page, how to do this? In the Craft CMS, there is the concept of entry types where you select the desired type and the "blueprint" get's updated. This action was still possible and very useful not just while creating a new entry, but also for existing ones. So if you have a blog post with 2 layout variants like "Hero image content" or "Three column layout", you could simple switch and while switching, optionally some additional fields appear.

When working via a code editor, `blueprint: three-column` should be used, but in the CP its not possible?

**Comment by vladdu** [comment]
I'm not sure if this is exactly the same issue, but a collection can have multiple blueprints. From what I see, when creating a new entry, the first blueprint in the list is used. One should be able to choose, right? Is that what you mean too, @steveooo1?

**Comment by steveooo1** [comment]
@vladdu Yeah, you should be able to switch `blueprint` via the CP. It's possible in the code, so it also should be in CP, esp. because of it's much needed use. If not, then this is some issue I would consider using it because we use this concept of entry types (here solved via different blueprints) everytime as a core-feature in previous Craft CMS projects.

**Comment by jasonvarga** [comment]
I think it's fine. Having multiple blueprints on a collection is our equivalent of Entry Types in Craft.
You could select a fieldset in v2, too, and when you refreshed you'd get the updated fields.

**Comment by jackmcdade** [comment]
Alrighty then, let's switch this from "doesn't work" to "Add feature" so we can support it properly.

**Comment by jasonvarga** [comment]
It doesn't work though. You can have a blueprint field - even just a text field where you type the handle - and it doesn't do anything when you save.

**Comment by steveooo1** [comment]
You can do this, Jason, I believe in you!

**Comment by steveooo1** [comment]
@jasonvarga Was this fixed with this? https://github.com/statamic/cms/commit/e027ea6d462ba4ff792db947237fa55ef6b0e53c

**Comment by steveooo1** [comment]
@jasonvarga Any update on this? This feature is essential for the decision if we use Statamic because it is a core feature we require for our websites and we used on other CMSs before.

To summary: A way to create a Blueprint field to change the `blueprint` parameter via the UI. So we could show and hide fields needed or not needed for this particular blueprint. A blueprint would be used as a way allow our clients to choose the "design layout" of the entry.

**Comment by steveooo1** [comment]
@jasonvarga @jackmcdade Any new infos? We are considering our next upcoming projects to be with Statamic and this is a must-have feature for us, so it would be great to know how the progress is. Thanks guys!

**Comment by steveooo9** [comment]
@jasonvarga @jackmcdade After the new beta with the newly done blueprints, I hoped that this feature request is now implemented, but it does not work.

When creating a `blueprint` named field, e.g. as a Select field, everything displays correctly, but when I change it and click save, the blueprint key doesn't get updated. (Also: Where is the blueprint fieldtype? :))

I really hope this gets added before launch, because our agency needs this feature and it doesn't seem to be a complex task (maybe it is?)

**Comment by jackmcdade** [comment]
@steveooo9 It didn't make it in because it wasn't mission critical for launch. The complexity has nothing to do with it. Even a simple feature can take a few hours to implement, write tests and documentation for, and so on. A few hours a few more times and we'll be another week into the future. 

Right now we're basically feature locked to get 3.0 launched and into the world. I know you said you really need it, so hopefully you can hang tight, or perhaps tackle it as a PR. 😊

**Comment by steveooo9** [comment]
@jasonvarga I love you! <3
