### ISSUE TITLE
slugify modifier wrong umlauts

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#1478]
gerät = title
{{ title | slugify }} output is gerat, but should be geraet .

**Comment by Konafets** [comment]
It doesnt work because the Modifier `slugify` does [not take the language into account](https://github.com/statamic/cms/blob/master/src/Modifiers/CoreModifiers.php#L1670). However, the called function `Stringy::slugify()` is able to take an language parameter and convert umlauts when `de` is passed as the 2nd parameter. See https://github.com/statamic/Stringy/blob/master/src/Stringy.php#L1167 and https://github.com/statamic/Stringy/blob/master/src/Stringy.php#L1859
