### ISSUE TITLE
Bard: Empty paragraph tags when adding set

### ISSUE THREAD

**Issue by tobiaseichert** [statamic/cms#1491]
My observation is that you'll always end up with additional paragraph tags right in front of the set when adding it, regardless of the existing type of content. Is there a way to remove those tags without deleting them manually?

Version: v3.0.0-beta.19

_Originally posted by @tobiaseichert in https://github.com/statamic/cms/issues/619#issuecomment-597201446_

**Comment by sauerbraten** [comment]
We have a custom Fieldtype that wraps Bard.php and we save content in the old legacy format, so we do override the original `process()` method with something like this:

```php
public function process($value)
{
    $value = parent::process($value);
    $value = (new Augmentor($this))->withDisabledSets()->withoutAugmentingSets()->augment($value);
    if ($value == '<p></p>') {
        $value = '';
    }
    return $value;
}
```

**Comment by tobiaseichert** [comment]
Thanks. Preferably, this should be the job of Bard when editing content. For now, I think I'll stick with the default.

**Comment by jesseleite** [comment]
Just wanted to note that it currently adds a blank paragraph before _AND_ after the newly added set...

![2020-05-16 17 14 06](https://user-images.githubusercontent.com/5187394/82130367-c4c09500-9798-11ea-9ae7-ccd5fdc5f36d.gif)

**Comment by joroe** [comment]
I am experiencing the same problem as @jesseleite describes. A fix would be great! Thanks!

**Comment by jmartsch** [comment]
I don't know, if all maintainers handle this the same, but in some other repos normally you would add a thumbs up to the issue. The maintainers then can sort by thumbs up to see whats most important to users.
Giving a thumbs up instead of a "me too" or "+1" comment is much better IMHO because it keeps the discussion clean and to the point.

**Comment by kodeine** [comment]
I am having the same issue, any fixes yet?

**Comment by fitzage** [comment]
Just ran across this. Same issue: blank paragraphs both before and after any set I add.

**Comment by lukeagsmith** [comment]
From an interface perspective I actually this the way Bard adds the space is a nicer experience for the average user. There is a nice big space for their cursor rather than the thin black insertion line you get if you manually delete the empty para.

I think a good fix would be when the following exists in the `yaml`
```
-
  type: paragraph
-
```
it simply doesn't get augmented into a new `text` type and thus doesn't make it to the view.

FYI I'm currently doing the following to handle it but obviously this isn't ideal or pretty:
```
{{ if type == "text" }}
	{{ if text != "<p></p>" }}
		<div class="container  container-narrow  px-4  lg:px-8">
			{{ text }}
		</div>
	{{ /if }}
...
```

**Comment by fitzage** [comment]
It is getting pretty tedious deleting the extra spacing around a set each time I add one.

**Comment by jmartsch** [comment]
Same
