### ISSUE TITLE
Bard-Fixed-Toolbar in Replicator-Fieldtype isn't sticky

### ISSUE THREAD

**Issue by WiebkeVog** [statamic/cms#1724]
## Bug Description
In a Replicator-Fieldtype, the Bard-Fixed-Toolbar is overwritten by 'position: relative'. Should the Bard-Fixed-Toolbar not be sticky in a Replicator-Fieldtype?

In the following code snippet we made the bard-fixed-toolbar sticky inside a Replicator-Fieldtype. If a Bard-Fixed-Toolbar is set in a Bard-Fieldtype that is placed in another Bard-Fieldtype, it will still not be sticky.
https://pastebin.com/AfPGsiFS

## How to Reproduce
1. Make sure that the toolbar_mode is fixed
2. Place a Bard-Fieldtype in a Replicator-Fieldtype
3. Scroll the page until the toolbar should stop at the top
4. Toolbar isn't sticky

## Environment

**Statamic version:** 2c0592a

**PHP version:** 7.3.14

**Install method (choose one):**
- Fresh install from `statamic/statamic`
- Starter kit
- Existing Laravel app
- Other (please explain this magic!)

**Comment by jackmcdade** [comment]
The sticky mode is only available by design when Bard is a top-level fieldtype. The UI can look really funky and broken when it's smaller, line wrapping, etc.

**Comment by Swennet** [comment]
@jackmcdade We get quite a few questions from our clients asking why the fixed toolbar is not working in bard fields in replicator content. This is especially inconvenient for them, since we use replicator fields as "page builders" in which bard content can become quite long.

Is there any chance this could get looked at again?

**Comment by fixr-austin** [comment]
> @jackmcdade We get quite a few questions from our clients asking why the fixed toolbar is not working in bard fields in replicator content. This is especially inconvenient for them, since we use replicator fields as "page builders" in which bard content can become quite long.
> 
> Is there any chance this could get looked at again?

@jasonvarga Re:  #11028
It would be very beneficial to have the fixed toolbar specifically when working in a bard field in replicator content for our "page builder" as @Swennet has mentioned. I totally understand the limitations due to the funkiness of the UI, but in the specific case of 1 full-width bard inside replicator content, could we make an exception?

**Comment by macaws** [comment]
Would love it if we could make this at least an option for content editors!

**Comment by duncanmcclean** [comment]
If you'd like to see this added, please add a 👍 reaction to the related feature request: statamic/ideas#1066
