### ISSUE TITLE
Localization not working correctly on replicator fieldtype

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1827]
The link url is set to `localizable: false`, so it should not be editable but is.

It seems to happen in replicator fieldtypes.

<img width="892" alt="Screenshot 2020-05-14 at 13 34 47" src="https://user-images.githubusercontent.com/38906163/81929769-e2023180-95e7-11ea-9272-e06fb8f88de0.png">

![Screenshot 2020-05-14 at 13 35 59](https://user-images.githubusercontent.com/38906163/81929772-e4648b80-95e7-11ea-9338-960718bc3f28.png)

## Environment

**Statamic version:** 3.0.0.-beta-28

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jonassiewertsen** [comment]
It seems, that the replicator `localizable` setting will overwrite settings from all replicator sets. 

Let me know if you need more information for this behaviour.

**Comment by jonassiewertsen** [comment]
Replicator sets don't have the translatable icon and am missing the option to link them to the default language.

<img width="953" alt="Screenshot 2020-05-14 at 13 56 22" src="https://user-images.githubusercontent.com/38906163/81931867-0dd2e680-95eb-11ea-9c51-53d197ff5095.png">

**Comment by jasonvarga** [comment]
Only top level fields are localizable at the moment. This means the entire replicator, not the individual fields.

**Comment by alexanderhofstaetter** [comment]
We are also highly interesed on translating the replicator fieldtype! We have several data structures where we need the replicator and on multilanguage sites we heavly rely on them.

I think all fieldtypes need to be translatable otherwise we cannot translate existing sites e.g. where the structure is fixed and cannot be changed very easily!

The current workflow is not very understandable for our clients, for example we sync the replicator fields to a different language:

- When there is no translated content for a replicator field (the data gets copied from the original source yaml file)
- When changes occur to the original content: Even when content is synced there are no changes in the translated content
- Due to the fact that the content is locked for translation (as it should sync from the original content) a client can never make changes without editing the yaml file!

**Comment by ddm-studio** [comment]
Same goes for us - we would really appreciate some improvements here: we would like have the opportunity to decide whether a replicator field should be localizable or not.
Often, it's required to have localizable fields and others which aren't, in order to avoid unnecessary work.

**Comment by jasonvarga** [comment]
Please open an issue in statamic/ideas.
But in honesty, this feature wouldn't be implemented for a while.

I'd suggest considering a different approach if you must have all the fields translated.
Maybe instead of replicator fields, have a separate collection(s) and then use `entries` fields to relate where appropriate.

**Comment by Diewy** [comment]
See: https://github.com/statamic/ideas/issues/439

**Comment by Payetus** [comment]
I understand that only top level elements be localizable. But at least it's a bug in the UI cause u are able to localize the field in the set.
![image](https://github.com/user-attachments/assets/9a0488f4-10bf-436b-8eb1-794828269bcb)
![image](https://github.com/user-attachments/assets/51e1c1e2-ea98-4fe2-bec8-cd9371b1de9d)
It feels like it's localizable 
But then you get a readonly in the entry
![image](https://github.com/user-attachments/assets/2e26df57-8d6a-4a5b-a29e-5c98ae8b7a0f)
