### ISSUE TITLE
Bard: Unwanted type: paragraph

### ISSUE THREAD

**Issue by robbinworks** [statamic/cms#1837]
Hey,

I know this has kinda already been reported but I wanted to raise an issue I have using the bard field.

As previous issues have brought up the bard field adds unwanted `type: paragraph` fields all over (i'm unable to remove these from the control panel, only way that works for me is to open said file in my editor and manually remove these lines).

Also, this seems to force me to create a partial called `text`, otherwise statamic blows up with the following exception:

```
Facade\Ignition\Exceptions\ViewException
View [sets._text] not found.
```

this is my code in the template:

```html
{{ sections }}
  {{ partial src="sets/_{type}" }}
{{ /sections }}
```

My current workaround is to create an empty file; `/resources/views/partials/sets/_text.antlers.html` to render the site without errors, preferably i would like to be able to remove these paragraph type fields from the control panel.

Any ideas?

**Statamic version:** v3.0.0-beta.26

**PHP version:** 7.3.16

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
This is the way it's intended to work. The "paragraph" set is rendered as a `text` type. The data that's stored in your YAML isn't the same as the data you work with in your templates, due to [augmentation](https://statamic.dev/augmentation).

So in short, if you want to use that dynamic/automatic partial method, you 100% of the time _must_ have a `text` partial.

More docs on Bard here: https://statamic.dev/fieldtypes/bard

**Comment by robbinworks** [comment]
I see, I've been developing sites in v2 for a few years and been using bard fields since it came out, it never worked that way/bloated my markdown files before, hence the confusion.

**Comment by jackmcdade** [comment]
Correct, Bard in v3 has some "under the hood" differences. We have a blog post all about it here: <https://v3.statamic.com/blog/bard-reimagined-again>
