### ISSUE TITLE
Blueprint names are case sensitive in yaml

### ISSUE THREAD

**Issue by austenc** [statamic/cms#1851]
## Bug Description
This only seems to happen on linux. When you assign a blueprint name in a yaml file, the name needs to be all lowercase or it won't work. I typed out a blueprint name into an entry's front matter without using the control panel and received an error. Correcting the blueprint assignment to use the lowercased version fixed this. 

## How to Reproduce
Manually (in the yaml file) assign a blueprint to an entry like this:
```
blueprint: Services
```
(this is assuming the blueprint name is "Services")

## Extra Detail
This will spawn an error like 
```
Call to a member function ensureFieldPrepended() on null at APP_PATH_HERE/vendor/statamic/cms/src/Entries/Collection.php:225)
```

## Environment

**Statamic version:** 3.0.0-beta-28

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
This will be because Linux is a case sensitive operating system. 

Meaning if you have a file called `Services.md` for example but you try and get it as `services.md`, Linux will report back and say the file can't be found. MacOS and Windows have different behaviours around this.

I wouldn't really consider this to be a Statamic bug, more of an incompatibility between operating systems.

**Comment by austenc** [comment]
Thanks @damcclean! I forgot I even opened this issue, it was early on in my v3 testing... otherwise I would've closed it sooner. 

👍
