### ISSUE TITLE
Consolidate date_format config

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#2019]
## Bug Description

We have `date_format` in `system.php` and in `cp.php`. We should probably only have one.

Or maybe it makes sense to have both, but we should confirm why.

## Environment

**Statamic version:** 3.0.0-beta.33

**Comment by ebeauchamps** [comment]
My 1 cent: in the cp the date format should be unique and respect the user defined date format, wherever a date is displayed. We have been struggling with this since statamic2, especially when you want to display the cp in another language than English AND you also want long date formats (with the written day of the week or the written month of the year). By the way, date-pickers should also be adjustable for the first day of the week...  I don't quite see any interest in having some dates in one format and others in another format within the app

**Comment by jasonvarga** [comment]
Absolutely.

**Comment by vladdu** [comment]
I don't see any reason to have two formats, but in case you decide to keep both, please document the choice. 

Is there maybe a third place to specify the format? The date picker shows the value in US format, regardless of what the php settings say.

**Comment by wesort** [comment]
Please keep open. Related to #1310

**Comment by jasonvarga** [comment]
I don't think we can combine them, as they do different things. I've adjusted the comments to better explain them. Goes along with #3730
