### ISSUE TITLE
[i18n] Fieldtype titles should remain in English

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#2034]
## Bug Description
Fieldtype descriptions are translatable, but fieldtype titles should remain in English in my view
i.e. for the Select Fieldtype I am now getting "Choisir" which is the French verb for Select

Some Fieldtypes are translated but not all of them, which doesn't help understanding what is on display.

Another solution: make all Fieldtype titles translatable, but in a way we can choose a different translation from the one in used in another part of the CP for the same word.

## Extra Detail
![Capture d'écran 2020-07-06 20 49 49](https://user-images.githubusercontent.com/1823359/86628564-5cd54080-bfca-11ea-8fb7-38a5ca814e65.png)

![Capture d'écran 2020-07-06 20 53 14](https://user-images.githubusercontent.com/1823359/86628853-c81f1280-bfca-11ea-818f-d9f864e30a0b.png)

![Capture d'écran 2020-07-06 20 53 21](https://user-images.githubusercontent.com/1823359/86628861-cc4b3000-bfca-11ea-9133-d2f49597412c.png)

## Environment

**Statamic version:** 3.0.0.-beta-{34}

**PHP version:** 7.{4.2}

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by helloDanuk** [comment]
You can manually add all fieldtype names in the json file now.

But I agree with your thoughts. There are similar issues in german: i.e. the select-fieldtype should be translated different from the word 'Select' used in another parts of the CP too. 

On the other hand, most of the names would be the same throughout the CP. Duplicate all names would unnecessary blow up the json file.

For german, the following words should be different:
- Link
- Select

But that may vary for other languages. So It might be better, if the fieldtype names are not translated at all? Then the reference to the docs would also be easier. We did this in german with 'Blueprint' and 'Fieldtype' – they are not translated. 

@Konafets What do you think about that?

**Comment by Konafets** [comment]
I am on the edge here. While I would use the CP in english, I made the translation PR because I know from the past that my customers are wanted german translations (not for Statamic in particular, but web applications I built in general). So I assume having a good german translation could make an impact on acceptance in germany mainly for editors / users.

To me the word "Blaupause" for Blueprint sounds weird, but its the correct translation and for a user who is not very fluent in english this might be better to understand. 

I am with @ebeauchamps to have it consistent – either translate all or none of the field type titles. And if we translate all of them I would vote for a dedicated translation string for them.

**Comment by ebeauchamps** [comment]
@Konafets @helloDanuk I think the Doc issue cannot be looked upon. Fieldtypes are referred to in the Docs with their English wording, and we won't have translated docs in the near future (tremendous task!). Therefore, I would personally go with English now.

**Comment by helloDanuk** [comment]
My motivation for the translation in general was that customers can use the CP more familiarly and easily. I also made the experience that English can be a hurdle.

However, normal content editors will hardly ever edit a blueprint. If someone does this, it requires an in-depth knowledge of Statamic, including reading the documentation.

I have translated everything, except when I consider it typical for Statamic and a translation can cause confusion (names like *taxonomy, blueprint, fieldset…*), when it gets technical (like *root, static cache*) or when we use the word also in German (like *template, commit*).

With fieldtypes we have both: Some are very clear (*color, date, user roles…*) and would be easy to translate. Others I consider names (*Bard, Blueprint, Replicator…*), which I would never translate, so that the reference to the documentation and screencasts remains comprehensible.

To avoid a mix-max and because the editing of blueprints is mostly left to the developers, I vote for not translating the fieldtype names.

But if they are translatable, they should be separate from other translations in the CP! So that we can use an understandable different translation for the same English word if it's needed.

**Comment by ebeauchamps** [comment]
OK with you

**Comment by jasonvarga** [comment]
So what's the final verdict here?

1. Translate them all.
2. Translate only ones that have common words like "Text" or "Color" and don't translate ones like "Bard" or "Replicator".
3. Hardcode English titles for all of them.

Seems like option 2 is the way to go.

**Comment by ebeauchamps** [comment]
For @helloDanuk and @ebeauchamps  the best solution is 3. Hardcode English titles
This decision is mainly related to the Documentation and to inappropriate translations as of today.
Thanks

**Comment by helloDanuk** [comment]
Yes, 👍 for 3. Because:
- The references in the docs are clear
- The blueprint builder is mainly used by devs and not by content editors

_But if 3 is not a option for you, they should all be translated in a language file as separate strings (1), so we don't get confused translated fieldtypes names: The english word 'Select' has a different translation throughout the CP as the word used for the fieldtype 'Select' (i.e. in de and fr)._

**Comment by Konafets** [comment]
I am fine with option 3 as well.

**Comment by helloDanuk** [comment]
OK github-bot, the issue is not yet solved – just be patient

**Comment by ebeauchamps** [comment]
;-)

**Comment by jasonvarga** [comment]
Is using the English word for all the fieldtypes still the preferred solution?

I'd be fine with dedicated translation strings for fieldtype names, if people think that's better.
