### ISSUE TITLE
Field types: 'Grid' and 'replicator' name swapped?

### ISSUE THREAD

**Issue by maries24** [statamic/cms#2057]
## Bug Description
Not sure whether that's an actual mistake or a naming issue.

Personally I would swap the names of the 'Replicator' and 'Grid' field types.

'Replicator' sounds like something that is repeated over and over. (Similar to the repeater in WP ACF)

'Grid' (and its icon!) evoke different sets of fields that can be re-ordered. (Similar to layouts in WP ACF)

## Environment

**Statamic version:** 3.0.0.-beta-36

**Comment by benfurfie** [comment]
I'd be cautious about doing this. This has been the naming convention for as long as I've been using Statamic (since 2015). That said, it's possible we could investigate rename the grid to something that makes a little more sense. I've never been a massive fan of the name.

And the Grid is actually broadly analogous to the repeater in ACF, while the Replicator is 100% analogous to ACF's Flexible Content.

**Comment by jasonvarga** [comment]
Even if we agreed, it's way too late to change now. Would confuse everyone.
