### ISSUE TITLE
Sidebar width can be weird and ugly

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2081]
## Bug Description
When removing the slug from the sidebar, the sidebar becomes very narrow. It's not pretty. Would be nice to have a defined min-width. Maybe even have a defined width altogether. It feels weird to have the sidebar jump around in size depending on its content.

## How to Reproduce
Remove the slug from the sidebar.

## Extra Detail
<img width="1265" alt="Bildschirmfoto 2020-07-15 um 11 07 36" src="https://user-images.githubusercontent.com/23167701/87527201-1055c900-c68c-11ea-9730-d0cb4bceb9d2.png">

## Environment

**Statamic version:** 3.0.0.-beta-37

**PHP version:** 7.4.6

**Install method (choose one):** Fresh install from `statamic/statamic`

**Comment by twd3** [comment]
Is that a collection? How did you get rid of the slug? I tried to and it just came back because it's required?

**Comment by damcclean** [comment]
I'm able to replicate this bug and it seems to happen on the latest release for me, even if I have a slug in the sidebar. 

![image](https://user-images.githubusercontent.com/19637309/93140332-29094c00-f6da-11ea-8845-6986304f3597.png)

I agree that the sidebar should probably have a set width instead of just doing whatever it wants 😂
