### ISSUE TITLE
Taxonomy: Creating new term on the fly in entry edit screen doesn't apply blueprint defaults

### ISSUE THREAD

**Issue by sebszocinski** [statamic/cms#2142]
When creating a new taxonomy term in the entry edit view it does not apply any fields with default values from the blueprint. 

This is an issue due to my other related issue #2003 where you can't set a default layout or template for a taxonomy so instead i'm doing it using hidden fields with default values for `template` and `layout` inside my blueprint.

Because it doesn't set these defaults, my routes are broken because i'm using custom folder structure's as per the docs [here](https://statamic.dev/views#organizing).

## Environment

**Statamic version:** 3.0.0.-beta-40

**Comment by jasonvarga** [comment]
The default blueprint values are intended to only be the defaults for when you actually use the forms.

If you want defaults to cascade down from the taxonomy into all of its terms, you should use `inject`.

```
# content/taxonomies/tags.yaml

title: Tags
inject:
  foo: bar
```

```
# content/taxonomies/tags/rad.yaml

title: Rad
```

```
# the term's view

{{ foo }} // bar
```

**Comment by venux92** [comment]
@jasonvarga is there a way to access the injected values in `/tags` rather than the term `/tags/rad`

For example I do have a page for `/tags` based on `taxonomies/tags.yaml` but I have no options to set meta tags which I could do in a terms but adding some fieldsets.

Any suggestions on how I could approach this?

I tried to access {{ $page->foo }} but it does not exist.

Thanks
