### ISSUE TITLE
Title field always moves to the beginning of the blueprint

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2173]
## Bug Description
Since `3.0.0-beta.42`, the `Section Fieldtype` can't be at the beginning anymore.

## How to Reproduce
Add a field of `type: section` as the first field of a blueprint. It won't display as the first.

## Extra Detail
**3.0.0-beta.42:**

<img width="942" alt="Bildschirmfoto 2020-08-03 um 20 17 44" src="https://user-images.githubusercontent.com/23167701/89214340-eaef1780-d5c6-11ea-9b15-72e97200dade.png">

**3.0.0-beta.41**

<img width="927" alt="Bildschirmfoto 2020-08-03 um 20 17 30" src="https://user-images.githubusercontent.com/23167701/89214351-f3475280-d5c6-11ea-9571-79c2cfc0bf86.png">

## Environment

**Statamic version:** 3.0.0.-beta.42
**PHP version:** 7.4.6
**Install method:** Upgrade from 3.0.0.-beta.41

**Comment by jasonvarga** [comment]
Looks like it it's not anything to do with the section fieldtype specifically. You can use any fieldtype. It's just that the `title` field always pushes itself to the top.

**Comment by jelleroorda** [comment]
Is there a reason why the title should be prepended? I'm fine with 'working around' the fact that there should be a title field (since I can use `display:` to alias the field differently in the interface), but I'm not sure why it should be the first field of the collection?

My use case to explain:
I have a collection 'people', of which every person has:
- initials
- preposition (optional)
- last name

I also prefer to show the fields in 33% width, in the order listed. In this case I would like to alias 'title' to 'Last name' (since this would be the logical choice of the three). Right now I would have to alias 'initials' to 'title' which is not intuitive, or I would have to accept that the order would be:
- last name
- initials
- preposition

I've checked the code at `Statamic\Entries\Collection:239` (Statamic 3.0.11) where it seems as easy as changing `ensureFieldPrepended` to `ensureField`. Depending on the way you look at it, I personally don't think this would be a breaking change (of course I understand if you think differently).

Any thoughts on this (or maybe work around I've failed to see)?

**Comment by jasonvarga** [comment]
Sorry, to confirm:

The title field should always be there. If you don't have one, it'll get plopped at the top. That's expected.
We want it at the top because it's probably the most important field. Putting it at the end is weird.

However if you put a title field *somewhere* in your blueprint, it should not *move* it to the top. That's the bug.
