### ISSUE TITLE
Git User isn't the authenticated User when Queued

### ISSUE THREAD

**Issue by Buffalom** [statamic/cms#2192]
## Bug Description
When using the git integration Statamic tries to use the authenticated user's name and email for the commit. When the commit job is queued however horizon does not have an authenticated user and therefore always uses the fallback user and email.

## How to Reproduce
Enable the git integration and use eg. redis (not sync) as the queue driver.

## Extra Detail
I understand that the job should use the fallback user when delayed because it will then group changes from several users but if the job is not delayed it would be nice if the authenticated user is passed to the job and used instead.

Is there a reason why this isn't implemented that way? You are also changing the message based on whether the job is delayed or not and the same could be done for the user.

## Environment

**Statamic version:** 3.0.0.-beta-43

**PHP version:** 7.3.13

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
In the documentation about using the Git integration with queuing, it does say that it will use the fallback Git details set in your `config/statamic/git.php` file instead of Git's authenticated user. 

I'm not sure it would be technically possible to use the authenticated user but then again I've not delved inside the Git integration stuff.

[See here.](https://statamic.dev/git-integration#queueing-commits)

**Comment by Buffalom** [comment]
I know it is currently intended that way but it would be nice if the authenticated user would be passed to the queued job if it isn't delayed.
