### ISSUE TITLE
Date conditional validation not working inside Grid

### ISSUE THREAD

**Issue by MikeHarrison** [statamic/cms#2201]
## Bug Description
I have a Grid fieldtype with two `date` fields in it - `start_date` and `end_date`. When the `end_date` has a validation setting of `after:start_date`, I can still choose an earlier date than `start_date` and save successfully, without a warning.

## How to Reproduce

- Create new Grid fieldtype
- Add `date` fields for `start_date` and `end_date`
- Set the validation for `end_date` to be `after:start_date`
- Select an `end_date` prior to the `start_date` and click save

## Environment

**Statamic version:** 3.0.0.-beta-43

**PHP version:** 7.2

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
When you do `after:start_date`, it's talking about a top level field named `start_date`.

If you want to target the `start_date` inside the grid, you should do `{this}.start_date`. However, this hasn't been implemented yet. Keep an eye open for when #1703 is closed.

Closing this because it's essentially the same issue.
