### ISSUE TITLE
Full measure static caching - Don't cache pages where content type is not text/html

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#2287]
## Bug Description

If you cache an xml page, the first request would be served as xml, but then the html file would be served as html which is incorrect.

## Extra Detail

See https://github.com/statamic/cms/issues/2259

**Comment by SenseAndImage** [comment]
I am reviving this. Currently content types other then HTML will all be served as HTML files. That is ugly when trying to use static caching for non-html files. For example JSON works when trying to access it via an SPA, however sitemap.xml does not work, since the xml file is not present at all.

I would prefer if statamic respects the mime type in e.g. routes/web.php

Tee following does not work when static caching is enabled (or has to be excluded from static_caching.php):
```
// The Sitemap route to the sitemap.xml
Route::statamic('/sitemap.xml', 'sitemap/sitemap', [
    'layout' => null,
    'content_type' => 'text/xml'
]);
```

**Comment by duncanmcclean** [comment]
@SenseAndImage Could you open a new issue for that please?
