### ISSUE TITLE
Cache corruption problem (or something)

### ISSUE THREAD

**Issue by fitzage** [statamic/cms#2290]
##  Bug Description
As I’m developing locally, I occasionally run into an issue where the entire site and control panel return the error `Call to a member function selectedQueryColumns() on null` as [described here](https://benfurfie.co.uk/articles/how-to-fix-the-call-to-a-member-function-selectedquerycolumns-on-null-error-in-statamic-3). The fix mentioned in that article, clearing the cache with `php please cache:clear`, fixes the problem until it happens again.

## How to Reproduce
I’ve heard of other people having the issue, but I haven’t been able to determine what triggers the problem. So far it’s seemed to happen when I’m working on navigation structures. I’m not sure if that’s only when it happens, or if that’s just when it cropped up.

## Environment
Statamic 3.0.0 Pro
Laravel 7.25.0
PHP 7.3.17
No addons installed

- Fresh install from `statamic/statamic`, followed by migration from v2 with the migrator

**Comment by damcclean** [comment]
I think this issue is caused when there's a different version of entries in your files than there is in the 'stache'. 

For example, it could happen if a developer switches branches from one that has loads of content to one that doesn't.

This issue also crops up quite regularly on the Statamic Discord.

**Comment by damcclean** [comment]
I'm closing this issue in favour of the above mentioned issue.
