### ISSUE TITLE
Remove user route model binding

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#2316]
Any of our routes with `{user}` will insert a Statamic user class.

For developers with existing Laravel apps, there's often a good chance they're using `{user}` in their own routes. Our route model binding screws it up for them.

We should remove the binding, or if there's a way to only do it for CP routes, do that.

**Statamic version:** 3.0.2

**Comment by deslittle** [comment]
Just came across this same issue when trying to install in an existing Laravel app. Would also prefer if Statamic did not affect my existing controllers.

A quick workaround is to remove existing User route model binding instances and get the user model myself from the Request in my app controllers.

Perhaps as suggested in [https://laravel.com/docs/8.x/routing#explicit-binding](https://laravel.com/docs/8.x/routing#explicit-binding) instead of binding all User bound routes using `Route::bind` you could use the `resolveRouteBinding()` function to bind each route created by Statamic.

**Statamic version**: 3.0.7

**Comment by stuartcusackie** [comment]
'form' is another statamic bind that is likely to conflict with an existing app.

I was thinking that prefixing each statamic bind, e.g. stat_user, stat_form, in the RouteServiceProvider would solve it, but then I have no idea of how much statamic code would have to be updated after that change.

**Comment by icemancast** [comment]
Believe my error here is related in an pre-existing admin area. `Object of class Statamic\Auth\Eloquent\User could not be converted to string`

https://flareapp.io/share/V7jQ3zJP#F71

**Comment by damcclean** [comment]
I've submitted a pull request to fix this issue: #3088.
