### ISSUE TITLE
String translation file output in collection list view filter

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#2342]
## Bug Description
Yeah, weirdest thing. I've got a files called `resources/lang/language/site.php` to use string translations: `{{ trans:site.previous }}`or whatever. 

With the files called `site.php` i get the following screen when switching to the tree view for the page collection:
<img width="1507" alt="Screenshot 2020-09-01 at 13 41 15" src="https://user-images.githubusercontent.com/69107412/91845492-8f618980-ec59-11ea-8e60-6ae044e617b5.png">

## How to Reproduce
Add a string translation file called `site.php`. 

## Environment
Statamic 3.0.2 Pro
Laravel 7.26.1
PHP 7.4.6
No addons installed

**Comment by jasonvarga** [comment]
Ha, weird.

We could work around that by adding an English json translation file with 1:1 strings, but that's a bit redundant 🤔 

Like this:

```
{
  "Site": "Site":,
  "Something": "Something",
  "etc": "etc"
}
```

Usually we'd just have the non-English json files since `__('Something')` would naturally just fall back to `'Something'`.

I'm inclined to just say don't use a translation file named site (or other words that might be used throughout the app) and close this for now.

If this becomes a real problem for more people, we can look at finding a proper fix.

**Comment by robdekort** [comment]
Maybe it should just be documented somewhere in the translations docs?
