### ISSUE TITLE
Permission helper text in CP is missing for Users and Updates (in translation permissions.php files too)

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#2483]
## Bug Description
The permission helper text is missing for the 'Users' and 'Updates' sections in the CP. 
Additionally you may only need the first view_users_desc for 'Users'. All others (create, delete, change, edit) are obvious, respectively there is no help text for them at 'Assets', 'Taxonomies'. At least I would make it identical everywhere.

If you add them to the CP, they should also be translatable.

## How to Reproduce
- Go to the 'Roles & Permissions' Page in the CP
- Create a new Role
- Hover over options in the users and updates sections

<img width="692" alt="Bildschirmfoto 2020-09-20 um 16 54 02" src="https://user-images.githubusercontent.com/8265902/93714282-e6c08e80-fb61-11ea-8e5b-ff831a30c9a8.png">
<img width="694" alt="Bildschirmfoto 2020-09-20 um 16 54 17" src="https://user-images.githubusercontent.com/8265902/93714293-efb16000-fb61-11ea-977c-e4071e2a4527.png">

## Environment
Statamic 3.0.10 Pro
Laravel 7.28.3
PHP 7.4.6
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
That probably means no one in the community has translated those strings yet. Which language have you got setup for viewing the Control Panel in?

**Comment by ebeauchamps** [comment]
@damcclean This was already reported a long while back, but the issue that was listing all remaining untranslatable keys has been closed by @jasonvarga because he had trouble seeing what was solved or not. I understand that.

But nonetheless, there still are some parts of the CP that are not translated, and some like this one above where the keys are not even existing in English.

We (translators) are using "php translator generate" to generate any missing keys in our language files, but sometimes the php translator fails to generate those keys.

I understand you want to help the gentlemen by commenting on issues (as @robdekort or @edalzell ) but those i18n issues are somewhat particular, so you just cannot write "the community has not translated it yet"!

**Comment by helloDanuk** [comment]
Thank you for commenting on this issue. I worked on the `de`/`de-CH` translation and the now closed confusing issue #1697. To move on with those open translation issues, I thought it would be best to open them 1 by 1 (or combine them if the problem is similar), so they will be more manageable. I might find some time for this during next week.

There is no urgent need for me to close them soon, my clients use V2 sites and my first V3 site and migrations are planned for next year. But when I am ready, I would like to be able to give them a professional look of the CP and for me this includes all translations. I appreciate the hard work the gentlemen are putting into all the open bugs and that others are more important at the moment – I can truly understand that it is a difficult time right now for them – please try to get enough sleep. Statamic is a 🚀 to everything I was ever looking for!

@damcclean As of the permission helper text issue above, it's in english the same problem. You do not need a translation to see these missing strings.

**Comment by damcclean** [comment]
Thanks for your explanation, I nearly know anything about how the translator works so just presumed the community ones were out of date. Sorry about closing.

I'll reopen now.

**Comment by helloDanuk** [comment]
💨🤖
