### ISSUE TITLE
Custom 503 error template not working

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#2570]
## Bug Description

Custom 404 error and custom errors layout work as described in the doc here :
https://statamic.dev/routing#error-pages

But for 503 image the custom layout is not used.

## Extra Detail

I've tried to use default Laravel template like so :

```bash
php artisan vendor:publish --tag laravel-errors
```

And it's perfectly working.

## Environment

```bash
Statamic 3.0.14 Pro
Laravel 7.28.3
PHP 7.4.10
4rn0/statamic-v3-image-optimizer 1.0.4
jimblue/htmlmin 1.0.0
jimblue/instagram dev-develop
jimblue/mapbox 1.0.0
jimblue/webpacker dev-develop
statamic/seo-pro 2.0.14
```

**Comment by damcclean** [comment]
This looks like this is a Laravel issue to me... 

Statamic has control over returning the not found pages (that's why layouts work there). 

However with 503 pages, it relies on [Laravel's maintenance mode](https://laravel.com/docs/8.x/configuration#maintenance-mode) feature which I don't think is Statamic can't really override.

**Comment by piljac1** [comment]
@damcclean You can add the following code at the top of the `render`  function of `app\Exceptions\Handler.php` to specify a view when in maintenance mode.

```php
if ($exception instanceof \Illuminate\Foundation\Http\Exceptions\MaintenanceModeException) {
    return response()->view('errors.under_construction');
}
```

Of course you can add some additional logic to support different locales if you have a multi-site setup. In my case, I only have "en" (main locale) and "fr" locales, so I added the following.

```php
if ($exception instanceof \Illuminate\Foundation\Http\Exceptions\MaintenanceModeException) {
    if ($request->is('fr/*') || $request->is('fr')) {
        return response()->view('fr.errors.under_construction');
    }

    return response()->view('errors.under_construction');
}
```

Of course, you can make it dynamic by retrieving available sites/locales with `config('statamic.sites.sites')`, but I kept it brain dead because I only have one additional locale.

**Comment by jimblue** [comment]
Agree with you @damcclean, it should be better for Statamic user to handle custom error template with Antlers.
It should work out of the box not only for **404** error but also for **503** and all others like suggested in the doc here : https://statamic.dev/routing#error-pages

**Comment by jelleroorda** [comment]
I'm experiencing the same issue, but then with `500` errors; I have customized the Exception handler with some code to render the exceptions. You can look at `Statamic\Exceptions\NotFoundHttpException` to see how Statamic usually renders antlers templates.

**Comment by jelleroorda** [comment]
Would be nice if this could be fixed still.

**Comment by damcclean** [comment]
I'll let @jasonvarga chime in but from what I can tell, there's no way for a Laravel package to override the exception handler stuff for 500 errors. The only 'fix' I think Statamic could really do is add a fix to the official starter kits in it's Exception handler.

**Comment by jasonvarga** [comment]
It seems to work fine for me.

If I have a 500.antlers.html and a route like

```
Route::get('derp', function () {
    throw new \Exception('Oh crap');
});
```

Visiting /derp shows me my antlers view.

If I have a 503.antlers.html and run php artisan down, I see that antlers view.

However, they both only use the template and not the layout. I don't think we can do anything about that. I'll put a note in the docs.
