### ISSUE TITLE
All structures id's are duplicated in structure when saving new order.

### ISSUE THREAD

**Issue by twd3** [statamic/cms#2662]
I have a simple orderable collection. When I just went and changed the order (only on two entries) via the cp and then tried to save that new order. I got the "something went wrong" error when trying to save order and then when i refreshed the CP it was broken because apparently when I tried to save that new order it duplicated every id in the structure so in my log I got "Duplicate entry [a91386d3-54d2-49c5-a861-67ccf38bcea7] in [testimonials] collection's structure." I do see that every id has been duplicated. The only way I can fix this because the id's are all mixed in with each other is delete the entire structure.

Make collection that is orderable, reorder in CP and try to save new order. I get error and then cp busted because every id in structure duplicated.

I am updating to 3.0.18 and retesting right now. I'll video the test and if it fails again I'll post video...

## Environment
Statamic 3.0.16 Pro
Laravel 7.28.1
PHP 7.4.6
jimblue/htmlmin 1.0.0
silentz/akismet 2.1

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by twd3** [comment]
Yup, still happening on 3.0.18

[Video_of_issue.zip](https://github.com/statamic/cms/files/5386560/Video_of_issue.zip)

**Comment by damcclean** [comment]
I see the issue in your video but I seem to be unable to replicate. I followed these steps:

1. In Collection Settings, enable Ordering, with descending order and a max depth of 1.
2. Save the Collection
3. View the collection entries listing, click the 'Reorder' button.
4. Move an entry to another position.
5. Save order
6. View collection entries listing, it displays fine.

I see from the video that you're using Windows, maybe that could be the cause for the issue or maybe it's caused by the amount of entries you have in that collection.

**Comment by twd3** [comment]
Yeah, I just tried it on an orderable collection that only has around 30 entries and it works fine. I have 160 in this other one.

**Comment by damcclean** [comment]
Just managed to reproduce this issue. I generated 160 random entries in a collection, [using this script](https://gist.github.com/damcclean/cef26fa418296de633f8a15beae66c98). Then I turned on collection ordering, and re-ordered a couple of entries.

I'm not sure what the 'breaking point' is where it decides to stop working.

**Comment by twd3** [comment]
Cool script! You're awesome for taking the time to believe in crazy Tom. Have no idea what's going on here.

**Comment by twd3** [comment]
As far as I know, this is still an issue. I wouldn't close it.

**Comment by jezzdk** [comment]
@duncanmcclean @twd3 This happened to me today as well. 
I have a collection with 53 items. I'm showing 50 items per page. If I go to page 1, click "reorder" and then immediately click "save order", I get a "duplicate entry" error.
However, if I'm showing 100 items per page, then the order is saved without any error. 

It seems to happen when re-ordering a list that spans multiple pages.

**Comment by o1y** [comment]
Here is a reproduction case for further debugging:

1. Clone this repository: https://github.com/o1y/statamic-collection-structure-exception
2. Go to the pages collection.
3. Click "Reorder" and then "Save".

Result:
```
local.ERROR: Duplicate entry [d3d495c6-c7b5-4cf4-8740-b39fcde7119a] in [pages] collection's structure.
```

The error is caused by the slugs on certain entries: if you delete all the entries that have a slug ending with `_xyz` (in my example repository the files are `2022-02-02.2022-02-02_test`, `2022-02-20.2022-02-20_testtest`, `2022-03-25.2022-03-25_tt` and `2022-05-23.2022-05-23_qq`), the entries can be reordered as expected.
