### ISSUE TITLE
Multisite: Toggle fields not working

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#2694]
## Bug Description
If you have a toggle field and activate it, on the default site, width `{{ if toggle }}` the content is shown on the default site, but not on the multisite. The "localizable" is set to `false`.

## How to Reproduce

1. Add toggle field to the blueprint
1. Set toggle to true
1. Add `{{ if toggle }}` to the template

Result: Default page shows content, multisite not.

## Environment

**Statamic version:** 3.0.19

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Please paste the md files of the origin entry and the localized entry.

**Comment by Pfeifakopf** [comment]
Hmm, I've compared the files. The multisite version contained the toggle fields with false as value. But normally this shouldn't be added, when the other language was clicked in the cp, right? 

Perhaps there was a change of the localizable value from true to false, so that the toggle field content was written in the past.

When I change the blueprints, are the fields getting updated with the next saving in the md files? If not, perhaps they should synced and fields deleted, when the localizable is set from true to false.
