### ISSUE TITLE
Collection filter in Control Panel does not work with associated collections

### ISSUE THREAD

**Issue by globalexport** [statamic/cms#2742]
Searching associated content of linked collection items does not work properly.

## How to Reproduce
On a fresh installation, create two collections and use the "Entries" field type in the blueprint to link items of one collection to items of another collection. Then try searching according to the linked items. 

Using "contains" condition will give no result. 
Using "is" condition brings up the error
"strtolower() expects parameter 1 to be string, array given" in
`/statamic/vendor/statamic/cms/src/Query/Builder.php#178`:

![Filter-Error.png](https://user-images.githubusercontent.com/70586640/97170584-3a8b4c80-178c-11eb-8d7d-2dcf464f525f.png)

## Environment
Statamic 3.0.20 Solo
Laravel 6.19.1
statamic/ssg 0.1.0
PHP version:** 7.3.20

**Install method (choose one):**
- Starter kit

**Comment by robdekort** [comment]
I don't get the error, however I did notice you can't search for linked items. It only works when you search directly for the ID of the linked item. That's not really practical ;-)

**Comment by robdekort** [comment]
🦥

**Comment by joseph-d** [comment]
This issue seems to occur for associated collections and associated users (like an 'author's field for example) but it seems to work properly for taxonomies.

Selecting a taxonomy field replaces the "is / contains" dropdown and accompanying text search with a single dropdown populated with available taxonomy items which can then either be selected or filtered. 

Because of this, in my opinion the "expected behavior" for choosing an associated collection from the filter list should be the same as for taxonomies (ie: no "is / contains" dropdown) for consistency.

**Comment by wautersj** [comment]
As @joseph-d stated, I would also expect it to work like filtering by taxonomy.

The filter knows (or should know) in which collection (based on specifications defined in the associated field) it should find matching ID's based on the inputed search text.

**Comment by duncanmcclean** [comment]
It looks like these issues have been addressed since it was discussed:

When filtering an Entries field, you can filter using the entry title:

![CleanShot 2023-11-01 at 12 08 48](https://github.com/statamic/cms/assets/19637309/cff67b3f-e56e-439e-b01e-aa8678be5260)

When filtering Terms or Users, it'll provide a dropdown with the relevant options:

![CleanShot 2023-11-01 at 12 13 14](https://github.com/statamic/cms/assets/19637309/a01a46dc-db73-46d1-86ff-a3eb8e380963)

![CleanShot 2023-11-01 at 12 14 36](https://github.com/statamic/cms/assets/19637309/d652cb73-ad2d-428d-b102-ef3feb71550a)
