### ISSUE TITLE
Bug with format_localized modifier and Laravel 8

### ISSUE THREAD

**Issue by jmartsch** [statamic/cms#2880]
## Bug Description
I upgraded Statamic to 3.0.29 (problem also appears with Statamic 3.0.28) and Laravel 8.0.15 via `composer update -W` (using composer 2).
When I clear the stache via the admin panel I get this error:
```
Facade\Ignition\Exceptions\ViewException
Argument 1 passed to Carbon\CarbonInterval::setLocalTranslator() must implement interface Symfony\Component\Translation\TranslatorInterface, instance of Carbon\Translator given, called in /home/www/dotnetic-statamic/vendor/nesbot/carbon/src/Carbon/Traits/Difference.php on line 803
```
See Stack Trace https://flareapp.io/share/x7XgzKXP#F62

This seems to come from my blogteaser partial, which includes the tag `{{ date format_localized="%d. %B %Y" }}`. 

The problem occurs, when I try to clear the stache via the control panel and I had the problem even on the frontend, when displaying the page that uses this code https://dotnetic.de/blog, but the page works now, sadly without localized date in german.

Everything works fine on my local dev environment. I really don't know where to look for the error.

## Environment

Statamic 3.0.28 Pro
Laravel 8.15.0
PHP 7.4.5
cnj/seotamic 2.0.2
octoper/statamic-inline-assets 4.0.2
rias/statamic-markdown-highlight 1.0.4
spatie/statamic-responsive-images 1.4.0
statamic/ssg 0.2.0

**Comment by damcclean** [comment]
Hmm, I seem to be unable to replicate on the latest version of Statamic (v3.0.30) 🤔

I created a new dated collection, created an entry with a date on it. Then in my template I used the same code to output:

```
{{ publish_date format_localized="%d. %B %Y" }}
```

And when I looked at the page in my browser I got the expected output (`21. November 2020`) instead of an exception.

By any chance have you done anything custom with Carbon instances? I'm guessing the issue doesn't go away after clearing the stache? `php please stache:clear`

**Comment by jmartsch** [comment]
I just made a complete new installation of Statamic and copied over my contents. Now this does not throw an error anymore, but my date is not localized anymore (german locale should be used, but english is used instead, I open a separate issue for that)
