### ISSUE TITLE
API should respect Future Date Behavior setting, not show drafts by default

### ISSUE THREAD

**Issue by fitzage** [statamic/cms#2910]
## Bug Description
- When using the API, items with future dates are returned by default, ignoring the Future Date Behavior setting on the collection
- This seems like unexpected behavior
- I’d rather pull the list and have to explicitly override that setting.
- This would allow my code to not already expose the necessary toggle to anybody who decides to look at the underlying code to see what they can find.
- Related to this, I feel that the API shouldn’t expose draft content at all until such a point as it has authentication available
- Perhaps also overriding the future date behavior should also require authentication

## Environment
Statamic 3.0.30 Pro
Laravel 7.25.0
PHP 7.3.17
statamic/seo-pro 2.0.14

**Install method (choose one):**
- Fresh install from `statamic/statamic`, migrated from v2

**Comment by damcclean** [comment]
As discussed on Discord yesterday.

I think this could potentially bring in a breaking change for production sites that are built upon this being possible. It could potentially be fixed by introducing a new configuration option, which would allow for future entries to be accessed for sites that don't have the new config option.

**Comment by jelleroorda** [comment]
My 2 cents... though it's definitely true that this would be a breaking change, I think it is still beneficial to do it since not showing 'unfinished content' should not be opt-in. Providing an opt-out would make the breaking change more acceptable to people who already built sites on this. I don't think that there's any site (that gets created after implementing this change) that would opt-out, since a flag along the lines of `published=false` seems to be the natural way?

But like I said this is just my opinion, I'd love to hear what the team thinks and am willing to contribute a fix if that's appreciated (but please do provide the general gist you would be looking for).

**Comment by jelleroorda** [comment]
For now the workaround is to filter out drafts yourself by adding `filter[status:is]=published` to the filters. If you need drafts you can use `filter[status:is]=draft` instead.

**Comment by jasonvarga** [comment]
I'm fine with it being changed to respect the date settings. It should. It's not a breaking change, I'd say its a bug fix.

**Comment by jackmcdade** [comment]
This was addressed a few months ago, we just missed closing the issue. Please reopen if not the case!
