### ISSUE TITLE
Collection: Entry Search case sensitivity

### ISSUE THREAD

**Issue by crackAT** [statamic/cms#3071]
## Bug Description
You can only search with a case sensitivity search term at the collection index page. 
A Article with the Title "Test" will not be found if you search for "test". 

## How to Reproduce
Test search with case sensitivity terms.
## Extra Detail

![image](https://user-images.githubusercontent.com/6299060/103661703-50c53e00-4f6f-11eb-8767-af7db00d810f.png)

## Environment

Statamic 3.0.36 Pro
Laravel 8.20.1
PHP 7.3.11
4rn0/statamic-v3-image-optimizer 1.0.4
phpsa/statamic-analytics 1.0.0
statamic/eloquent-driver 0.1.0

**Install method (choose one):**
- Existing Laravel app

**Comment by jasonvarga** [comment]
If you haven't [connected an actual search index to the collection](https://statamic.dev/search#connecting-indexes) then it'll do a more basic query. Since you're using the Eloquent driver, your database might be set up to be case sensitive. What kind of DB are you using?

If you connect a search index (which you probably will want to do) it should be case insensitive. Bonus if you use Algolia, you'll get cool stuff like typo tolerance.
