### ISSUE TITLE
Headless mode with disabled routes?

### ISSUE THREAD

**Issue by ajnsn** [statamic/cms#3138]
## Bug Description

If you set `'enabled' => false`in `config/statamic/routes.php`, you cannot access the control panel.

Instead you will get a `RouteNotFoundException` with message `Route [statamic.site] not defined`.

Add `statamic.site` to `routes\web.php` will allow to access the Control Panel but selecting anythin in the sidebar will return a `Page not found` in the content section.

```php
Route::any('/{segments?}', [FrontendController::class, 'index'])
    ->where('segments', '.*')
    ->name('statamic.site');
```

Is there any other recommend way to use the API and the Control Panel only?
Thank you!

## How to Reproduce

- `composer create-project --prefer-dist statamic/statamic statamic-test`
- Set `'enabled' => false` in `config/statamic/routes.php`
- Open `/cp` in the browser.

## Environment

Statamic 3.0.39 Solo
Laravel 8.23.1
PHP 7.4.14

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
This is to be expected, as that's where you disable **all** of Statamic's routes, including those for the Control Panel and the API.

To use no front-end routes for a headless site, just don't give collections routes and leave your layout blank.

**Comment by ajnsn** [comment]
I see, will do!

`vendor/statamic/cms/routes/routes.php` shows different if-clauses for `config('statamic.api.enabled')`, `config('statamic.cp.enabled')` and `config('statamic.routes.enabled')`, so my impression was that there *could* be an approach to allow this. In any case, we can close this now. 

Thank you for your fast answer!

**Comment by chiiya** [comment]
>This is to be expected, as that's where you disable all of Statamic's routes, including those for the Control Panel and the API.

Wouldn't say this is the expected behaviour at all. As @ajnsn commented, that setting only affects the _frontend_ routes. CP and API routes should still be active. In a headless CMS mode I want the CP and API routes, but explicitly _not_ the frontend routes.
Currently I'm solving this issue by overwriting the route with a simple redirect: 
```php
Route::redirect('cp/redirect/site', '/')->name('statamic.site');
```
That should not be necessary though. The CP code should either check if the frontend routes are enabled (`config('statamic.routes.enabled')`), or if the route exists (`Route::has('statamic.site')`. If not, it should fall back to `/` or simply not display the "View Site" link.
I can create a PR for this if you wish.
