### ISSUE TITLE
Select field only output and save "Label" 

### ISSUE THREAD

**Issue by philipboomy** [statamic/cms#3179]
## Bug Description

Select field only output "Label" but the docs https://statamic.dev/fieldtypes/select#templating says that I should get the value but I only label which is probably because my data is saved with the label instead of the value (key) which is different than the docs.

Setup: https://share.getcloudapp.com/rRukPjAl
Saved data: https://share.getcloudapp.com/wbu9y6qb

## Environment

Statamic 3.0.40 Pro
Laravel 8.22.1
PHP 7.4.14

**Comment by damcclean** [comment]
What does your field look like in your blueprint? 

Sounds to me like YAML parsing could be doing funny things because the values are 0, 1, 2, 3 etc. 🤔

**Comment by arthurperton** [comment]
Yes spot on @duncanmcclean: I did a test and you're right, the YAML parser makes a regular array from this (not an associative array) because of the integer keys. Therefore there is no way of distinguishing this:
```yaml
0: 'No Limit'
1: 2
2: 3
```
from this:
```
- 'No Limit'
- 2
- 3
```

Because (currently) the keys are optional, a non-associative list is interpreted as 'labels only' and then [the value and label will be the same](https://statamic.dev/fieldtypes/select). 

As far as I can see, the only way to avoid such problems would be making both the values and the labels mandatory.
