### ISSUE TITLE
S3 assets meta slows down site

### ISSUE THREAD

**Issue by goellner** [statamic/cms#3216]
## Bug Description

We are using the responsive image plugin from Spatie and run into super slow TTFB times. We are talking 3 seconds TTFB with 5 images on a page. I have narrowed it down now to s3 and it makes total sense, that its so slow and now I would really need some help about this issue. Whenever an asset is generated, it needs to fetch the meta information of an asset, those files are stored on s3 and not on the local disk, this could explain why it is so slow to fetch this information. I don't know if there is any workaround, to store the asset information on the disk instead of on s3.

I will set up a repository and S3 bucket for testing purposes and send you the credentials

## How to Reproduce
1. Setup assets via s3
2. Use responsive image plugin and make a page with a few images on in
3. Check slow TTFB

## Extra Detail
Tried setting cache true in `assets.php` but that didn't speed up things.

## Environment

Statamic 3.0.42 Pro
Laravel 8.26.1
PHP 7.3.25
spatie/statamic-responsive-images 2.4.3
statamic/seo-pro 2.1.1

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by goellner** [comment]
I have made a test suite for this: https://github.com/goellner/statamic-3-asset-test
Please write me on discord, so I can send you the S3 credentials for the `.env`, so you don't have to set up an s3 bucket for testing.

Its hosted here: https://statamic-assets.goellner.dev/

**Comment by jasonvarga** [comment]
Try adding `'cache' => true` to your `s3` disk in `config/filesystems.php`

**Comment by goellner** [comment]
Added it, shaves off a good amount. But still TTFB from S3 variants is pretty much double the time of local assets: https://statamic-assets.goellner.dev/

**Comment by jasonvarga** [comment]
I looked into this. Seems like a few bottlenecks.

1. The various "file exists" checks. These are all API requests to S3.
  
   Wherever we're checking if the asset exists is usually to prevent some other type of error. We could try to get around the file exists checks by handling the errors in a different way.

   One main example for these checks would be if you had an assets fieldtype, you select some assets, then one of them gets deleted. The asset would still be referenced in the entry and cause an error. Right now, we filter down the list depending on whether they exist.

2. If you're using Glide, then there's a validation step that checks the mime type for security. This is another API request.

   Assuming we cache the mime type into the meta as described in #3277, this should naturally speed up.

This isn't actionable for you, but I'm really just putting this here as a note to myself. 😄

**Comment by tao** [comment]
I would also like to add a note as this may be related, however I can open up another issue if it isn't. 

We have many entries (+1500) and they each have a PDF stored on Amazon S3. The load time is greater than 60s on the control panel when you open an entry to view or edit. This often gives us a 504 Gateway Timeout because it takes so long to load the page. I assume it's taking a long time because it tries to process all the meta-data or PDF files on S3. When I updated the blueprint and set it to a local assets folder the control panel page loads in 3s instead... so I know the bottleneck is with the assets on S3. 

I'm also running on a 50MB fibre line so I don't believe the slow loading comes from my side.

I have `cache_meta` and `cache` set to true in the config file but I assume it only caches images as the cache path is set to `img`.

We're not fetching any images at all on this collection, just PDF files... however other folders on S3 do contain images, but the blueprint is restricted to this one folder with only PDFs.

**Comment by GioChocolateBro** [comment]
@jasonvarga 

The exists calls on the folders inside Statamic\Filesystem\AbstractAdapter are really hammering us.

We solved it by changing this:
```
    if (! $this->exists($path)) {
        return $fallback;
    }
    return $this->filesystem->get($this->normalizePath($path));

```
To this:
```
    try {
        return $this->filesystem->get($this->normalizePath($path));
    } catch(\Exception $e) {
        return $fallback;
    }
```
Can we make a pull request for this?

**Comment by jasonvarga** [comment]
Yes

**Comment by jasonvarga** [comment]
3.1.0-beta.1 includes a ton of asset related improvements, mostly targeting S3 performance.

It would be great if you could check it out!

You'll need to set `watcher` to `false` in `config/statamic/stache.php`.

**Comment by goellner** [comment]
Updated the testing site at https://statamic-assets.goellner.dev/s3-glide and the speed is awesome now. One question regarding the stacked images in the debugbar timeline. Is there any way (a queue, redis,?) to have the image urls being generated at the same time as opposed to the waterfall we have now? 

Wether we use the glide or responsive image addon, it adds up quite a lot, when generating a srcset with lets say 10 images. we have sites with around 50-100 images on one page and 50 x 10ms is half a second for TTFB, we solve it currently by enabling the static cache, but if there is a way to just use a queue or something that would be the absolute last missing piece.

**Comment by jasonvarga** [comment]
If you aren't using the "cached" Glide setting, then the glide tag is just spitting out urls. It's not actually generating anything.
There's nothing to queue in this situation. The images would get generated when the browser tries to load the `<img>` tags.

If you are using the cached setting, images would be generated as the template is being rendered.
That's where I'd expect the most noticeable waterfall in the debug bar.
If we queued the image generation then the template would render faster, but you might have broken images since they wouldn't be ready by the time the page loads.

So yes we could add queueing, if you were okay with broken images initially.

Maybe I'm misunderstanding what you're asking though.

**Comment by tao** [comment]
@jasonvarga I can confirm it's much better on the 3.1-beta and solves the issue for us. It seems like we're getting 3-5s load times instead of +60s.

**Comment by jasonvarga** [comment]
I still don't love 3-5s but its much better than 60+ 😬
