### ISSUE TITLE
OAuth login overwrites user data

### ISSUE THREAD

**Issue by jeremydouglas** [statamic/cms#3269]
## Bug Description

When a user registers with OAuth, it can overwrite an existing user.

## How to Reproduce

1. Follow the docs to install OAuth
2. Setup a user by regular ol' email
3. Login with an account from an OAuth provider that uses the same email address as used in step 2
4. All values in the yaml user file created in step 2 are lost and only the values OAuth set remain

## Environment

Statamic 3.0.43 Pro
Laravel 8.27.0
PHP 7.4.10
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
Are you using flat file users or eloquent users with your oAuth setup?

**Comment by jeremydouglas** [comment]
Files. My test on this was a clean Statamic install with no customization.

Though, my actual app is using eloquent with a database and that's working well, as far as I know.

**Comment by duncanmcclean** [comment]
Okay, I'll try and remember to have a look this evening. My suspicion is that it's actually creating a new user when you login.

**Comment by duncanmcclean** [comment]
Yup, I can confirm this is a bug... 🐛

**Comment by MadeByMike** [comment]
For me this throws:

![image](https://user-images.githubusercontent.com/1320567/126026587-da5e09a2-c204-4305-aa39-3dd5f0db6363.png)

**Comment by sheldonkotyk** [comment]
I'm having the same issue after a google migration from one instance of google suite (free for non-profits) to another instance (enterprise) where the email addresses stayed the same, but the UUID changes. It is only for a few of my users though and I'm not one of them which is making debugging painful. 

Using flat files for my users.

I believe it may be relevant to what @duncanmcclean noted but it isn't only with users created with please first. It may be users in my situation. In fact, my user was created with please, and it is one that doesn't rewrite on each login.

**Comment by sheldonkotyk** [comment]
I've confirmed that it happens regardless of whether it is created via oauth, or using please. :/

**Comment by rustypaul** [comment]
I get the same issue here too, it just overwrites the user if it wasn't created by OAuth. 

Is there some way of customising the way Statamic/Laravel handles this? I was looking at this but the docs don't really give you a lot of info on how to customise it, especially when it comes to checking if a user should match.

https://statamic.dev/oauth#user-data

**Comment by ARCHES-Academy** [comment]
Any update on this? I've got the same issue. Trying to get Oauth to recognize my existing users and use them instead of creating new accounts.

**Comment by duncanmcclean** [comment]
Nope, there's no update. This is still on the list of things to fix. If anyone manages to find a workaround, feel free to post it here to help others.

**Comment by ARCHES-Academy** [comment]
Okay, so after much trial and error, this is the function I put together that seems to have solved it for me:

``` php
OAuth::provider('google')->withUser(function ($user) {
            $email = $user->getEmail();
            $existing = User::findByEmail($email);
            if($existing) {
                $existing->set('google_id', $user->getId());
                $existing->set('first_login', now()->format('Y-m-d'));
                return $existing;
            } else {
                return User::make()
                    ->email($email)
                    ->set('first_name', $user->getGivenName())
                    ->set('last_name', $user->getFamilyName())
                    ->set('first_login', now()->format('Y-m-d'))
                    ->set('google_id', $user->getId());
            }
        });
```

Do note that I haven't done much testing of the solution yet, but what little I've done has been successful. I manually created a user via control panel, and then logged in via Oauth to that users account (with the above function in the `AppServiceProvider.php`) and it found the correct user and updated it instead of creating a brand new account.

If anybody knows a better/simpler/more elegant way of doing this, feel free to refine this.

**Comment by MatteoGgl** [comment]
I'm having a similar problem: if a user is already registered to the platform (using the registration form) and later tries to login/register with an OAuth provider, statamic returns an Error 500: `Integrity constraint violation: 1062 Duplicate entry 'test@example.com' for key 'users.users_email_unique'`.

Statamic 3.2.16
Laravel Framework 8.64.0
PHP 7.4.3

@ARCHES-Academy fix worked for me, this is a shorter version that uses only the default statamic fields:

```php
OAuth::provider('google')->withUser(function ($user) {
            $existing_user = User::findByEmail($user->getEmail());
            if ($existing_user) {
                return $existing_user;
            }
            return User::make()
                ->email($user->getEmail())
                ->set('name', $user->getName());
        });
```

**Comment by jelleroorda** [comment]
In theory, when you have an application with multiple OAuth providers, I think you wouldn't want multiple created users for the same email address. For example: a user with email `foo@bar.com` authenticates with Github, then authenticates through Facebook with the same `foo@bar.com` email. It would be weird for that to create multiple users. This would create the same issue as described by OP. (I'm assuming you would get a different OAuth id for this usecase as well, haven't tested).

Question for the team:
1. Does this need to be fixed as in: the `findOrCreateUser` method on the `Statamic\OAuth\Provider` needs to look up users by email instead of the OAuth id?
2. Or can we fix this by adding some extra documentation about how to implement the above solution in case you have users that could potentially switch from email -> OAuth (or between multiple providers [?])?

From my perspective it would 'make sense' to implement option 1, since it seems weird that a developer has to implement 'proper' support for ensuring their users doesn't get overwritten. It looks like that solution would not be a breaking change since the users created by OAuth add the email address.

**Comment by arthurperton** [comment]
Hi @jelleroorda, I was just about to assign myself to this issue but then I saw your comment. Do you want to take this one on?

As for your question, I'd go in the direction of option 1, changing `findOrCreateUser`. My plans were roughly:

1. If a user is found by the provider name + socialite id --> great, return that
2. Otherwise try and find the user by email. When found, merge the socialite data info the data of the user that was found, save the user with the extended data and return the user.
3. When no user is found either way, create a new one using the socialite data.

Actually only step 2 would need to be added, the rest is already there.

**Comment by jelleroorda** [comment]
@arthurperton Sure, I'll have a hack at it later. Your proposed solution makes sense 👍

**Comment by arthurperton** [comment]
Cool, have at it!

**Comment by arthurperton** [comment]
Hi @jelleroorda, I am going to work on a PR for this one.

**Comment by jelleroorda** [comment]
All good, I haven’t found the time to make a fix.
