### ISSUE TITLE
Counting a collection alias before looping breaks stuff

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#3374]
The count modifier breaks the collection object when parsed afterwards.

```
{{ collection:blog as="entries" }}
    {{ entries | count }}
    {{ entries sort="title" }}
            <a href="{{ url }}">{{ title }}</a>
    {{ /entries }}
{{ /collection:blog }}
```

If you move the `{{ entries | count }}` underneath the loop, everything is fine. This feels like a parser issue.

**Comment by arthurperton** [comment]
I just looked into this one and your feeling was right, it is a parser issue.

The problem is that the parser mistakenly sees `{{ entries | count }}` as the opening tag for the entries tag pair.

I guess the hint for the parser would be that the tag contains a modifier, and therefore it can't be the opening tag.
