### ISSUE TITLE
yield content not parsed in partial

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#3399]
## Bug Description
The content from `{{ section:videos }}` is not shown inside partials.

## How to Reproduce

```
{{ section:videos }}
{{ videos }}
{{ /section:videos }}

{{ sections }}
{{ partial src="partials/sections/{type}" }}
{{ /sections }
```

```
// partials/sections/content

{{ yield:videos }}
```

`{{ yield:videos }}` is not parsed/shown.

## Environment

**Statamic version:** 3.0.47

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
Do you think this issue could be related to #3286?

**Comment by wm-simon** [comment]
I have tested different orders with no effect for it.

**Comment by duncanmcclean** [comment]
Thanks, just wanted to double check, in case you hadn't seen that issue.

Anyways, I've just attempted to reproduce this issue but I'm unable to see the issue. Where are you using the `{{ section }}` tag? In a layout, in a template, in a partial inside a template?

Also, do you have multiple yield/sections in that page?

**Comment by wm-simon** [comment]
I gave you access to the repo. The problem is shown on the url /karriere, which loads the view karriere/index .

There you can see `{{ section:content__after }}`. The section is loaded in partials/sections/text .

**Comment by duncanmcclean** [comment]
Thanks! I can see the issue. Here's a quick summary of the issue...

The site has a template for an entry. Inside that template, it is doing `{{ section:foo }} ... {{ /section:foo }}`. Under that, near the end of the template, it is looping through Replicator/Bard sets and using a partial depending on the set type.

```handlebars
{{ thingy }}
   {{ partial src="partials/things/{type}" }}
{{ /thingy }}
```

Inside the antlers template for one of the partials, it's doing `{{ yield:foo }}`, which doesn't seem to output anything to the page, which is where the issue lies.
