### ISSUE TITLE
Can't load collection because of `file_put_contents` issue on taxonomy

### ISSUE THREAD

**Issue by 1stevengrant** [statamic/cms#3432]
I've been migrating a site from v2 and running into this. The collection has about 1000 entries.

```
[2021-03-25 19:35:08] local.ERROR: file_put_contents(/Users/stevengrant/Sites/slcl/storage/framework/cache/data/stache/items/terms/recommendation_tags/default/): failed to open stream: Is a directory {"userId":"651791ed-3ffb-4657-80e5-d45192a0ff07","exception":"[object] (ErrorException(code: 0): file_put_contents(/Users/stevengrant/Sites/slcl/storage/framework/cache/data/stache/items/terms/recommendation_tags/default/): failed to open stream: Is a directory at /Users/stevengrant/Sites/suffolkv3/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:185)
[stacktrace]
```

I ran into this back in November when I did a dry-run and gave up. Had hoped it would have been gone by now. I can't understand where the `default` is coming from after `recommendation_tags`. If I remove the taxonomy, things load fine. If I create a new taxonomy and reassign the collection entries to use that taxonomy, I error out again.

Caches have been cleared, permissions are good too.

I've seen other reports of this in Discord but with no resolution.

```
Statamic 3.1.0 Solo
Laravel 8.34.0
PHP 7.4.16
```

**Comment by 1stevengrant** [comment]
I also have another taxonomy attached to the collection and that one seems to be fine.

I'm flummoxed.

**Comment by 1stevengrant** [comment]
Here's the full trace if useful https://flareapp.io/share/LPlAMND7#F106

**Comment by 1stevengrant** [comment]
another little update, I set the cache driver to use Redis instead and things are looking to be working as expected

**Comment by jasonvarga** [comment]
The issue was that in v2 there were taxonomy fields that looked like:

```yaml
mytaxonomy: ''
```

and running the migrator changed it to:

```yaml
mytaxonomy:
  - ''
```

I suppose when Statamic tries to create those automatic taxonomy terms based on what's in your entries, it chokes when it tries to create a term with no value.

The solution for this issue is to remove the empty taxonomy fields from those entries.

Here's something you can paste into `php artisan tinker` to automate it. Tweak as necessary with your collection and taxonomy handles.

```php
Statamic\Facades\Entry::query()
  ->where('collection', 'the_collection')
  ->get()
  ->filter(function ($entry) {
    return $entry->get('the_taxonomy') === ['']);
  })
  ->each(function ($entry) {
    $entry->remove('the_taxonomy')->save();
  });
```

We'll improve the migrator's handling of those empty fields, though.

**Comment by 1stevengrant** [comment]
thank you sir
