### ISSUE TITLE
Ability to change the order of the assets

### ISSUE THREAD

**Issue by ReneWeCode** [statamic/cms#3603]
Would be nice the be able to change the order of the assets. Example could be: Sort by the "Last Modified" - or even better, the date of the upload. But also change by asc/desc.

**Comment by ReneWeCode** [comment]
V 3.1.24: It's not possible to sort the assets at all. Not even by alphabetic desc/asc.
![Jun-18-2021 11-54-26](https://user-images.githubusercontent.com/43215436/122543373-0078fe80-d02c-11eb-9639-58ab16464bc9.gif)

**Comment by jasonvarga** [comment]
Closing this one since you can change the order of the assets now.

The header changes the sort order of the assets, not the folders. That's intentional, but maybe not such great UX.

This is sorta related to https://github.com/statamic/cms/issues/2829 where we discussed maybe taking the folders out of the asset listing.
