### ISSUE TITLE
User registration form with custom redirects has no error or success values in the response

### ISSUE THREAD

**Issue by goellner** [statamic/cms#3669]
## Bug Description
User registration form with custom redirects has no error or success values in the response. Needed to add a query param and now don't have access to the success or error values.

## How to Reproduce
```
{{ user:register_form redirect="{url}?test=true" error_redirect="{url}?err=true"}}
```

## Environment

Statamic 3.1.12 Pro
Laravel 8.40.0
PHP 7.4.15

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
So what you're saying is that you lose the query parameters whenever you are redirected from the `user:register_form`, correct?

**Comment by felixstoessel** [comment]
I have the same issue in a different context:

```
{{ form:create in="{{ form:handle ?? handle }}" }}
  {{ if success }}
    {{ success }}
  {{ /if }}
{{ /form:create }}
```

This worked fine some Statamic versions ago. Right now on 3.1.14, I don't get any success or error messages. When I have a form with some server side validations, those error messages also do not appear anymore. I tested this part of my code very intensively and there was nothing changed except updating Statamic with its dependencies.

**Comment by felixstoessel** [comment]
Soo, I tested the issue and I have some observations:

1. When I do a form submit, I get a 302 redirect. I checked my `.htaccess`, but every redirect there has a 301. If this redirect is not normal, then this should be the issue. Because when redirecting with 301/302, we lose the response data.
2. The URL is `/!/forms/contact`, where `contact` in my form handle.

But I am too stupid to fix this, because I have no clue where to look...

![redirect-on-submit](https://user-images.githubusercontent.com/13189565/119129426-3039e400-ba37-11eb-8406-afc6a1e25fdc.png)

**Comment by felixstoessel** [comment]
Well, the 302 redirect is the normal redirect via `back()`. I get my error messages inside `formFailure()` inside `FormController.php`. So either way after that is some issue with `session()` or some new or updated middleware logic...

**Comment by felixstoessel** [comment]
So, I tested every PHP part and in Antlers, right before me calling `{{ errors }}{{ value }}{{ /errors }}`, I created a dump:

<img width="490" alt="errors-dump" src="https://user-images.githubusercontent.com/13189565/119135846-3e8bfe00-ba3f-11eb-9251-3c0d669f50e4.png">

So the error messages are there, but somehow the augmentation of `errors` does not work.

**Comment by felixstoessel** [comment]
Is there anyone watching this issue? I find this bug to be important, because it really makes forms completely useless and very bad for customers (because of no feedback like success or errors)...

**Comment by felixstoessel** [comment]
@jasonvarga Could you help with that? I did more debugging than I wanted, but I have no idea how things are internally connected to fix this. Thank you!

**Comment by felixstoessel** [comment]
@jackmcdade Sorry to write to you guys directly, but this is a critical issue and I am very frustrated. Nobody seems to look at this despite having done some initial work to help fixing this bug. I wouldn't be so impatient if it wasn't a critical bug.

**Comment by jasonvarga** [comment]
The original issue is quite different from what Felix is explaining. They're not even the same tags.

Regarding the registration form, you never showed the template where you're trying to output the success or errors. Both `success` and `errors` are available on the tag. So if you're not using the tag, they won't just magically be available.

They do live in the session though, so you can use the `session` tag to grab them:

```
{{ if {session:user.register.success} }}
  {{ session:user.registesr.success }}
{{ /if }}
```

We'll update the docs.

As for the form thing, it looks like some weirdness when you use `??` instead of `or`. Changing `{{ form:create in="{ handle ?? form:handle }" }}` to `in="{ handle or form:handle }"` fixes it. I'll open a separate issue.
