### ISSUE TITLE
Permission error when user does not have Edit Other Authors Entries enabled.

### ISSUE THREAD

**Issue by cityofpae** [statamic/cms#3677]
## Bug Description
User cannot edit their own entries even with permissions that should allow this.

## How to Reproduce
Create user with appropriate permissions to edit,create,delete entries but do not allow 'Edit Other Authors Entries'.
User cannot edit their own entries, 
but if we enable 'Edit Other Authors Entries'.. the user can now edit their own entry.

![image](https://user-images.githubusercontent.com/22512770/117597074-f7228980-b183-11eb-8165-ad3ed8c27b88.png)

## Extra Detail
the author field in the editor is read only, but it is still trying to validate the field on pressing 'Save' and producing the following error.
ERROR MSG: 'Must be an array.' on the Author field.

![image](https://user-images.githubusercontent.com/22512770/117597015-d22e1680-b183-11eb-945b-0e4c5c0280dd.png)

## Environment
1. local development on MacOS
Statamic 3.1.12 Pro
Laravel 8.40.0
PHP 7.4.9
No addons installed

2. and also hosted on Digital Ocean
Statamic 3.1.12 Pro
Laravel 8.40.0
PHP 7.4.14
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jesseleite** [comment]
@cityofpae Having trouble reproducing this one 🤔

Can you share your entry blueprint, or maybe even upload/share a zip/repo with everything setup to see this error?

**Comment by cityofpae** [comment]
here are some files that might help..
[archive.zip](https://github.com/statamic/cms/files/6469954/archive.zip)

I have tested editing other collection type entries which do not have a 'users' field and it seems to work fine.
So it looks like it is an issue when including a 'Users' field in the blueprint and the validation kicks in even though the field has been made read-only due to the permissions (as shown in the original screenshot above).

Tommy

**Comment by helloiamlukas** [comment]
I get the same error. My entry has a field called `author`. The blueprint looks like this: 

```yaml
handle: author
field:
  max_items: 1
  mode: select
  display: 'Author'
  type: users
  icon: users
  listable: true
```

When a user is trying to save this entry (and he is not allowed to edit other authors entries) a _'Must be an array.'_ validation error will be shown.

The problem is located in `Statamic\Http\Controllers\CP\Collections\EntriesController`

https://github.com/statamic/cms/blob/687cd84bbfd86576c613fe5912fb1c95c8d8a41f/src/Http/Controllers/CP/Collections/EntriesController.php#L162-L164

This line overrides the `author` field with an integer value.

@jesseleite Can you reproduce this now?

**Comment by ayaone** [comment]
Having the same issue. On line 163 $entry->value('author') returns an integer, but array is expected.
In my case, we're storing entries in a database
