### ISSUE TITLE
Collection Term Details show.antlers.php wrong output in `{{ locales}}` tag

### ISSUE THREAD

**Issue by goellner** [statamic/cms#3833]
## Bug Description
Collection Term Details show.antlers.php wrong output in `{{ locales}}` tag

## How to Reproduce

Use this route from the taxnomy routing docs: The {collection_handle}/{taxonomy}/show view will be used. (eg. blog/tags/show.antlers.html)
Loop over your locales with the `locales` tag, check url. Url does not contain the collection handle

## Extra Detail
Shared via email

## Environment

Statamic 3.1.18 Pro
Laravel 8.40.0
PHP 7.4.20
aryehraber/statamic-captcha 1.4.0
doublethreedigital/duplicator 1.3.1
jonassiewertsen/statamic-livewire 2.5.0
mia/statamic-image-renderer 1.0.4
spatie/statamic-responsive-images 2.5.3
styriarte/jetticket dev-development
withcandour/aardvark-seo 2.0.11

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
@arthurperton Think you can take a look at this one?

**Comment by arthurperton** [comment]
Sure! It is a bit out of my comfort zone, but I’ll have a try.

**Comment by jasonvarga** [comment]
Sort of a note to self, or whoever: the issue here seems to be that the `locales` tag reaches into the "context" (the variables available to the parser at that position) for the `id`. It finds the id of the term, and grabs that term.

The way these magic collection specific terms work is that we gotta do `$term->collection($collection)`, and that's done when we load the route itself.

We should probably make the item itself (the `Term` in this case) available to the view somehow, and let the locales tag grab that instead of doing a new lookup.

**Comment by arthurperton** [comment]
@jasonvarga To be honest thus stuff kind of confuses me. Do you want to take this one? I think I can do more good on the PRs that I’m still working on.

**Comment by jasonvarga** [comment]
Yup, already for #4047 going for this.

**Comment by arthurperton** [comment]
Cool. I changed the assignment for clarity.
