### ISSUE TITLE
Filtering a Collection by a "related entry" should be smarter

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#3954]
In order to use an Entries field to filter a collection you need to map in the `id`. Ideally the tag should be smart enough to know it's an entry and pluck the proper field.

Example:

``` md
post: 123-123-123-1234
---
{{ collection:products :post:is="post" }} // this doesn't work
{{ collection:products :post:is="post:id" }} // this does work but it's not intuitive
```

And yes, I ignored the issue template. I slapped my own wrist.

**Comment by jasonvarga** [comment]
Just a note here...

The tag already has some smarts, which conflicts with the smarts you're wanting to introduce.

(I'm changing the parameter in the example above from `:post:is="post` to `:slug:is="post"` to make a little easier to understand, so you don't see postpostpostpost)

Using this piece of code:

```
{{ collection:products :slug:is="post" }}
```

It assumes you want the _slug_ from the entry you're passing in. It does that by looking at the parameter name. You end up with a query like:

```
$query->where('slug', 'slug-of-the-entry');
```

We added this feature because of basically the same reason you've opened this issue. You didn't want to have to do `:slug:is="post:slug"`.

It became even more useful when you had an array of entries:

```
{{ collection:products :slug:in="posts" }}
```

This would take the slug from each entry in the `posts` field, and pass it along. You'd end up with a query like:

```
$query->whereIn('slug', ['first-slug', 'second-slug']);
```

I 100% agree what you're asking for is a good idea, but I don't know how to support both without breaking something, yet.

**Comment by jackmcdade** [comment]
If we haven't figured this out by now, I expect we're going to live with it as is rather than introduce a potentially breaking change. Closing this.
