### ISSUE TITLE
Route Model Binding Exception

### ISSUE THREAD

**Issue by aerni** [statamic/cms#4108]
## Bug Description
[Route Model Binding as described here](https://statamic.dev/extending/addons#route-model-binding) doesn't work. It throws a `Call to a member function id() on null` Exception. 

The issue is `$route->parameter('collection')->id()`. The parameter `collection` does not exist.

https://github.com/statamic/cms/blob/c58e7b494854764b7dea10cab333cf127542b3f8/src/Providers/RouteServiceProvider.php#L61

## How to Reproduce

Add this route and a test view:

```php
Route::statamic('/test/{entry}', 'my_test_view');
```

## Environment
Statamic 3.1.32 Pro
Laravel 8.53.1
PHP 7.4.20

**Comment by edalzell** [comment]
Slugs are not unique anymore, not sure the best way to handle this

**Comment by aerni** [comment]
It works when simply removing the part that throws the error. But I'm not sure if it breaks something else.

**Comment by aerni** [comment]
But I want to use route model binding. What I'm after is creating a route that gets the full context like a regular collection entry does. Not sure if I'm understanding route model binding correctly.

This works. I see that the `entry` will be available in it's own variable instead of flattened like the data is:

```php
Route::statamic('/test/{collection}/{entry}', 'my_test_view');
```

I also tried to use a controller like [mentioned in the docs](https://statamic.dev/extending/addons#route-model-binding). But this throws an `Array to string conversion` exception at `vendor/statamic/cms/src/View/View.php:194` .

```php
Route::statamic('/test/{collection}/{entry}', [TestController::class, 'show']);
```

```php
class TestController extends Controller
{
    public function show($collection, $entry)
    {
        dd($collection, $entry);
    }
}
```

**Comment by duncanmcclean** [comment]
Not entirely sure if this is totally related to this issue but we're coming up against a couple issues regarding route model binding when installing Statamic into an existing Laravel application.

In our case we have an Eloquent model called `Asset` because our app is related to physical assets. However, now we've installed Statamic, this breaks as we're using route model binding.

This is the error we're seeing with any of the routes with `asset` route-model binding.

```json
{
  "message": "Call to a member function handle() on null",
   "exception": "Error",
   "file": "/home/the-project-in-question/vendor/statamic/cms/src/Providers/RouteServiceProvider.php",
   "line": 111,
}
```

In Statamic's `RouteServiceProvider`, it binds `asset` to a Statamic asset which is what's causing the conflict. 

https://github.com/statamic/cms/blob/3.1/src/Providers/RouteServiceProvider.php#L108-L120

We can potentially work around this by overriding the route-model binding ourselves and doing a check if the request is from the CP or not. If it is, we use Statamic's stuff, if not we bind to our own `Asset` model.

```php
$firstPath = explode('/', request()->getPathInfo())[1];

if ($firstPath === 'cp') {
  return $assetId;
}
```

This obviously isn't ideal - maybe Statamic could prefix it's bindings with `statamic`, so it's `statamicAsset` instead which would certainly cause less issues.

Using Statamic alongside existing Laravel applications are our primary use case - in fact, this is the third app that we're doing it on.

**Comment by jasonvarga** [comment]
Honestly I think we should remove our bindings. As you can see it conflicts with people's applications too much. We already removed one here https://github.com/statamic/cms/pull/3088

**Comment by ryanmitchell** [comment]
I just bumped into the same issue installing onto an existing Laravel app - `{collection}` was causing 404 issues.
It would be great if the bindings could be optional, or scoped to Statamic only.
