### ISSUE TITLE
Control Panel: Can't view or download assets of form submissions

### ISSUE THREAD

**Issue by RafaelKr** [statamic/cms#4514]
### Bug description

When you have a form with a file upload you can see a preview of the uploaded files in the control panel via `/cp/forms/{form}/submissions/{submissionId}`. But there is no way to view or download the original file.

### How to reproduce

- Create a form "Test" with an asset field
- Submit the form with an uploaded file
- View the form in the CP via Forms > "Test" > [The submission]
- You can now see a preview of the uploaded file but there is no way to view or download the original file

### Versions

Statamic 3.2.10 Solo
Laravel 8.48.0
PHP 7.4.24

### Installation

Fresh statamic/statamic site via CLI

### Additional details

I already created a PR to fix this: https://github.com/statamic/cms/pull/4379
Please also see this related issue in the ideas repo: https://github.com/statamic/ideas/issues/669

**Comment by FrankPeters** [comment]
This is great! We ran into the same issue today, I've overridden the blade view file for now to remove the `read-only` but that is just a workaround for now. Happy to see the PR, thanks a bunch! Hope it will be merged soon.

**Comment by FlorianMoser** [comment]
The `read-only` was only added on a recent update. Before, you were able to edit and then download the asset. This broke several of my client sites. This download-feature is an urgently needed update.

@FrankPeters did you just change the original `/vendor/statamic/cms/resources/views/forms/submission.blade.php` file or do I miss an option to overwrite CP views?

**Comment by FrankPeters** [comment]
@FlorianMoser Sorry I only see this now. We used Laravel's vendor override possibility. So created our own `submission.blade.php` in: `/resources/views/vendor/statamic/forms/submission.blade.php`.

**Comment by bynicolas** [comment]
I was about to create an issue on this topic as well. This also happens on collections with read-only asset fields.

So basically, if you set a field as read-only, then it's only possible to see the filename but we are not able to access the popup modal or link to the file directly for viewing in the browser.

So `read-only` is broken because it's not possible to read the file in any way (I'm referring to access from the `form submissions entries` or from the `collection entry page`, of course, it's still accessible from the assets manager)

**Comment by Buffalom** [comment]
I believe this has been solved in #6299 and published in [v3.3.18](https://github.com/statamic/cms/releases/tag/v3.3.18).

**Comment by RafaelKr** [comment]
Yes it was, thanks for reminding!
