### ISSUE TITLE
lang-files causing error

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#4852]
### Bug description

When you add a language-file at `/resources/lang/{lang}` with the same filename like a collection handle, there is shown an error on the backend.

### How to reproduce

Collection `aktuelles`
![image](https://user-images.githubusercontent.com/3351449/144615545-66471756-1ad4-4e61-8ddd-0c7c02516081.png)

Lang `aktuelles`
![image](https://user-images.githubusercontent.com/3351449/145365675-00bf0282-e357-4cf8-9251-ace0f55a9d3c.png)
Error:
```
htmlspecialchars(): Argument #1 ($string) must be of type string, array given (View: \vendor\statamic\cms\resources\views\partials\nav-main.blade.php)
```

### Versions

Statamic 3.2.24 Pro
Laravel 8.73.2
PHP 8.0.12    

### Installation

Fresh statamic/statamic site via CLI

**Comment by adevade** [comment]
In your screenshot, the `de` folder is not in the `lang` folder.

**Comment by wm-simon** [comment]
I've made a screenshot from the wrong folder, it was a backup. I've changed the screenshot.
Thanks for your hint.

**Comment by duncanmcclean** [comment]
Confirmed. I think this will be down to the fact Statamic allows to translate the collection name's. If a collection translation existed, it would get a string, otherwise it would fallback to the name of the collection.

However, what's happening here is that Laravel is looking up the translation for the collection name and getting an array, which the code isn't expecting, causing that exception to be thrown.

I'm not really sure if there's a great way to work around this (other than naming the language file something else). I'll let the Team decide on what the best approach is for this.
