### ISSUE TITLE
Improve `nav` tag performance

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#5254]
I'm seeing some significant performance issues with the `nav` tag, so have been experimenting with [a custom version](https://gist.github.com/jacksleight/467af74557bbf029cbd43cd3092f11f2). Check the gist for full details, but in my tests with a nav containing 50 items using the custom tag adds ~80ms, whereas using the default tag adds ~670ms.

I'm not suggesting these exact changes should be made to the core, and I'm sure there are better ways to implement the changes I've made, but it would be great if the performance of the core `nav` tag could be improved.

**Comment by jasonvarga** [comment]
You can now make the nav tag perform better by selecting the fields you need. See #5068

There have also been some other under the hood improvements.

**Comment by MattRogowski** [comment]
I didn't see any improvement from #4925 (unless I needed to do something else here) but massive improvements from #5068. The `nav` tags are still the slowest part of the site, but I've gone from ~3.5s load times to ~700-800ms which is a huge gain.

**Comment by simonhamp** [comment]
Ok, so following up on my crazy mad idea to add caching 'somewhere', I went on a hunt to find the best thing to cache. The most sensible place to start seemed to be close to what's already being `Blink`-ed, and the most generic place (between Collection Trees and Nav Trees) seemed to be the [`Tree::tree()`](https://github.com/statamic/cms/blob/0cc66c57404fd684ea72926d86a9b590a4ee4dce/src/Structures/Tree.php#L44-L55) method.

So first of all I wanted to get some idea of timing for the homepage of the site I'm working on, which uses 3 navs and currently takes in excess of 2 seconds to load pretty consistently.

<details>
<summary>Code</summary>

```php
public function tree($tree = null)
{
    $start = hrtime(true);
    $ret = $this->fluentlyGetOrSet('tree')
        ->getter(function ($tree) {
            $key = "structure-{$this->handle()}-{$this->locale()}-".md5(json_encode($tree));

            return Blink::once($key, function () use ($key, $tree) {
                return $this->structure()->validateTree($tree, $this->locale());
            });
        })
        ->args(func_get_args());

    dump((hrtime(true) - $start) /100000);

    return $ret;
}
```
</details>

So I add some quick and dirty [`hrtime`](https://www.php.net/manual/en/function.hrtime.php) calls around what's currently happening to get a picture and dump out the result. (NB: `hrtime` returns **nanoseconds**, so to get milliseconds, gotta divide by a million)

I basically get over 500 calls to the `tree()` method on this page. Seems excessive, but it's fine - if it's fast, 500 function calls can be over in a few milliseconds.

I make a request in the browser, copy-paste the dump output (basically 500 floats) and stick 'em in Excel. Tidy it up a bit, run a `=SUM` over those bad boys and get what I'll call **Total Milliseconds Spent in Tree™** (or _TMSIT_, for short) for one request.

Cool, rinse and repeat to get a sensible set of data that averages out. Obviously the more requests I do, the closer to some kind of normal my average will be. But I just want a quick sample to verify my method at this point that I can use as a gauge for when I've made some changes.

#### TMSIT (`Blink` only): ~1386

<img width="325" alt="Screenshot 2022-04-21 at 21 06 21" src="https://user-images.githubusercontent.com/31628/164543802-6a6c8579-6a3d-48a8-9b1e-93e0e9e87900.png">

Ok, so let's make a change. I just wildly replaced `Blink::once` with `Illuminate\Support\Facades\Cache::rememberForever()` (I know, this is probably not what I want in prod, but it's just for testing).

<details>
<summary>Code</summary>

```php
public function tree($tree = null)
{
    $start = hrtime(true);
    $ret = $this->fluentlyGetOrSet('tree')
        ->getter(function ($tree) {
            $key = "structure-{$this->handle()}-{$this->locale()}-".md5(json_encode($tree));

            return Cache::rememberForever($key, function () use ($key, $tree) {
                return $this->structure()->validateTree($tree, $this->locale());
            });
        })
        ->args(func_get_args());

    dump((hrtime(true) - $start) /100000);

    return $ret;
}
```
</details>

#### TMSIT (`Cache` only): ~1453

<img width="330" alt="Screenshot 2022-04-21 at 21 08 46" src="https://user-images.githubusercontent.com/31628/164544175-7e4990ce-5108-4eef-a9d3-ade23d3065a7.png">

Alright. Slower. Hmmm 🤔 ... right so `Blink` is going to be all in application memory. But my `Cache` driver is redis and although that's in-memory too, PHP has to call out to redis 500 times, so slightly slower. Makes sense.

But what if... let's mush the two together... firstly we `Cache` into redis, but once we've fetched it out we `Blink` it because `Blink` is faster... best of both?

<details>
<summary>Code</summary>

```php
public function tree($tree = null)
{
    $start = hrtime(true);
    $ret = $this->fluentlyGetOrSet('tree')
        ->getter(function ($tree) {
            $key = "structure-{$this->handle()}-{$this->locale()}-".md5(json_encode($tree));

            return Blink::once($key, function () use ($key, $tree) {
                return Cache::rememberForever($key, function () use ($tree) {
                    return $this->structure()->validateTree($tree, $this->locale());
                });
            });
        })
        ->args(func_get_args());

    dump((hrtime(true) - $start) /100000);

    return $ret;
}
```
</details>

#### TMSIT  (`Blink` + `Cache`): ~503

<img width="332" alt="Screenshot 2022-04-21 at 21 13 20" src="https://user-images.githubusercontent.com/31628/164544875-1c887af3-6eea-4fa9-9116-7cb1a26e4669.png">

Not bad!! Shaved off over 60%. Might call it a night.

Hol'up tho. I've been counting more than just my caches here... I've been counting this whole `fluentlyGetOrSet` call stack too _and_ the generation of that `$key` (note it does both `md5` and `json_encode`).

Ok, so, that's a bit of an unfair test. Let's move that timing mechanic to inside the `getter` callback.

<details>
<summary>Code</summary>

```php
public function tree($tree = null)
{
    return $this->fluentlyGetOrSet('tree')
        ->getter(function ($tree) {
            $key = "structure-{$this->handle()}-{$this->locale()}-".md5(json_encode($tree));

            $start = hrtime(true);

            $ret = Blink::once($key, function () use ($key, $tree) {
                return Cache::rememberForever($key, function () use ($tree) {
                    return $this->structure()->validateTree($tree, $this->locale());
                });
            });

            dump((hrtime(true) - $start) /100000);

            return $ret;
        })
        ->args(func_get_args());
}
```
</details>

Cool. Run a request....

<img width="182" alt="Screenshot 2022-04-21 at 21 26 10" src="https://user-images.githubusercontent.com/31628/164546711-c46fae60-9f44-4277-b00e-ebf24c1a39dc.png">

Holy, what? Let me check... yep same number of calls to the method - seems legit.

![](https://media.giphy.com/media/MoBklgH66BKxi/giphy.gif)

Ok so something is going on here that doesn't make any sense. Maybe this `fluentlyGetOrSet` is doing something that's not on the tin. Or maybe that `md5` + `json_encode` is going wild?

So I shuffle my timing code around - the `md5` + `json_encode` is negligible... like, well below negligible, as expected. That stuff is super fast, baked into PHP, basically C-code running right up against the metal.

At this point I'm almost certain that the `fluentlyGetOrSet` method is doing something funky so I dive in. It's in a trait that creates a new `FluentGetterSetter` object for each call - ok that seems a little unnecessary - but it looks like this class/object is basically just a proxy to get a value on another object... right?

<img width="609" alt="Screenshot 2022-04-21 at 21 35 34" src="https://user-images.githubusercontent.com/31628/164548043-5cbe8ebc-c103-4346-ac26-da092e8337f8.png">

Oh no! Reflection. What? Why? That's mega overkill.

I'm really not sure why we need this. Why can't I just access the class property directly? Why do I need this proxy class to do this work for me? Is it just some coding convenience/consistency thing? And I can immediately realise how I would achieve the same result _without_ it so what happens if I rip this out and do it the 'old-fashioned' way?

<details>
<summary>Code</summary>

```php
public function tree($tree = null)
{
    if ($tree) {
        $this->tree = $tree;
        return $this;
    }

    $key = "structure-{$this->handle()}-{$this->locale()}-".md5(json_encode($tree));

    $start = hrtime(true);

    $ret = Blink::once($key, function () use ($key, $tree) {
        return $this->structure()->validateTree($this->tree, $this->locale());
    });

    dump((hrtime(true) - $start) /100000);

    return $ret;
}
```
</details>

<img width="649" alt="Screenshot 2022-04-21 at 22 12 57" src="https://user-images.githubusercontent.com/31628/164553179-505d0d90-b6c0-4b64-9478-b49eb1d068ea.png">

#### TMSIT (`Blink` only): ~575
#### TMSIT (`Cache` only): ~893

This approach, **`Blink` only**, is _as fast_ as the `FluentGetterSetter` `Blink` + `Cache` - so nothing changes in output, only the way that it's put together. Easiest change to make, over 60% quicker.

But now I want to check to see if my initial one-off request that triggered this line of exploration (moving the `hrtime` into the fluent getter callback) was just a fluke, so I wire it all up run a few more requests with this new approach:

<img width="655" alt="Screenshot 2022-04-21 at 22 11 40" src="https://user-images.githubusercontent.com/31628/164553008-c509d117-07fd-496a-aec9-63c4f0eb4732.png">

### TMSIT (`Blink` + `Cache`): ~16

16 milliseconds!! No fluke. **That's almost 100x faster**. I think I might have nailed the `{{ nav }}` performance issues folks.

Ok, I know that `rememberForever` may not be the most appropriate caching strategy here and more work is likely to be needed in case a tree structure (either a nav or a hierarchical collection) gets modified in the CP - but I'm sure that's doable, I'm sure there are event hooks we can use or some other way to prime this cache on demand. It looks like it will be well worth the effort.

Going back to my homepage with all of this instrumentation turned off and my newly minted Fluent-less, `Blink`/`Cache`-d Tree (FLBCT™), I get a heartwarming and consistent sub-1-second response time for almost every page and no issues.

What's more, caching at this level (rather than at the template using `{{ cache }}`) avoids all of the caveats and potholes I mentioned in my previous message. Mega win 🎉 

Awwwwww, yehhhh

![](https://media.giphy.com/media/4UJyRK2TXNhgk/giphy.gif)

(Now I guess I gotta write a couple of PRs 🙄 )

**Comment by simonhamp** [comment]
Another follow-up:

So this isn't the whole story, obviously. I've been doing more digging and another 'problem' that I noticed is that `flattenedPages` attempts to do some sort of in-memory caching too (`$this->cachedFlattenedPages`), but fails to do it well enough.

The problem is, this is an _instance_ property only, so that cache will be isolated to a single `Tree` object. Useful if that single `Tree` object is reliably used throughout the request, but (for some reason) the exact same `Tree` can be represented by multiple _different_ object instances within the same request. That means that `cachedFlattenedPages` isn't providing as much benefit as it could do.

I haven't dug into why that's happening or if this means there's a 'problem' elsewhere, I'm just looking at patching that up a bit and a quick way to do that is with some memoization:

<details>
<summary>Code</summary>

```php
protected static $cachedFlattenedPages = [];

public function flattenedPages()
{
    $key = md5(json_encode($this->tree));

    if (array_key_exists($key, static::$cachedFlattenedPages)) {
        return static::$cachedFlattenedPages[$key];
    }

    return static::$cachedFlattenedPages[$key] = $this->pages()->flattenedPages();
}
```
</details>

My very basic attempts to test whether this improves matters revealed somewhere between a 10-15x speed up.

**Comment by simonhamp** [comment]
### Round 3

In my endless search for speed improvements (😅) I found another part of the navs which I'm certain could be speeded up: `Statamic\Tags\Structure::toArray()` - this is where the rubber meets the road for navs. It essentially takes the tree we've built (whether a NavTree or a CollectionTree) and turns it into a working loop of data for rendering in a template.

Unfortunately, even for small navs using `select="@shallow"` and other tricks, this can still take a couple-hundred milliseconds to compute. For example, I have a nav with 20 items and it take almost 100ms to build. We run that nav twice on the page for reasons, so that's almost 200ms spent building that one navigation.

Removing that would significantly improve performance site-wide. A simple approach is to throw `{{ cache scope="page" }}` around it and be done... but that means every request to a page that's never been requested before (and therefore has a cold cache) suffers the penalty of building that nav.

You could go with my earlier `{{ cache key="{site:locale}_nav_footer" }}` suggestion, but I dunno, that just feels super icky to me; **I really feel like navs should come out of the box with this sort of thing nailed!**

So, digging deeper: As hinted at by the introduction of `@shallow`, this largely comes down to how the augmented data is built, and we see the bulk of the time spent in `$page->toAugmentedArray($keys)` (2 or 3ms per page soon adds up). But we also see 1ms or 2ms used up in `$url = $page->urlWithoutRedirect()`.

This all easily adds up. Again, if your nav is anything like 20 items or more, you're going to be burning through your TTFB like nobodies business. Perhaps what's worse is that this has **absolutely nothing** to do with the size of your collections - it's completely linearly related to the number of entries used in a nav. Which means, as your nav grows, all your pages that use that nav slow down by the same amount.

The good news though is that these are all probably highly cacheable values - in a typical scenario, I imagine that once they've been computed they're quite unlikely to change. **(Please let me know if this isn't true for you!)**

Caching these values specifically (again, rather than the whole nav via `{{ cache }}`) means they can be re-used more widely (i.e. across multiple requests) _and_ the nav rendering stays mostly dynamic because we're caching the underlying data, not the outputted HTML.

That means, only the very first request to any page using a nav that references a specific entry (note, not tied to a specific nav!) with an unprimed cache takes the penalty. Following that, every subsequent request should be a cache hit _without_ losing things like dynamic styling based on `is_current` and `is_parent`.

This has massive implications for how navs perform - wherever you use any nav it will now prime a cache for every 'Page' object that is generated to support it. And that cache works across navs, pages, and 'Sites', **so even after just one page request, every nav on your site may be faster by the next request**.

And the even better news is, that I've [already added the necessary logic](https://github.com/statamic/cms/pull/5899/files#diff-35b2648e490b6e2ef111c9094125f8aa1df301ffbe4e5dbb9163ebd63a308c38) for this to my PR #5899!

I really truly believe that I'm done with navs for now 😂 

#### din-din-dingggg 🔔

**Comment by duncanmcclean** [comment]
I'm aware there's not been much activity on this issue for a while. 

However, I just wanted to add a note that we've made a bunch of high-impact performance improvements in Statamic 5, including to the navigation & tree stuff.

Hopefully updating to v5 should improve things significantly for some sites (if not, all sites).

**Comment by jasonvarga** [comment]
Nav tag is much better in v5. 👍

**Comment by simonhamp** [comment]
Have you done any profiling of the improvements? Would be nice to see how much faster it is by the numbers
