### ISSUE TITLE
Select fields still provide `LabeledValue` objects rather than actual values

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#5528]
### Bug description

Loving the fact that we dont need to worry about `Value` objects and calling `->value()` in Blade anymore! However select fields (and possibly others?) still return a `LabeledValue` object, so you do still need to call `->value()` for those.

### How to reproduce

Try to use a select field value in an expression such as `@if($entry->my_select)` or `$entry->my_select ?? 'Fallback'`, it will always be `true` as a `LabeledValue` object is being returned.

### Versions

Statamic 3.3.0 Pro
Laravel 9.5.1
PHP 8.0.15

### Installation

Existing Laravel app

**Comment by jasonvarga** [comment]
It's intentional. You get those so you're able to do `$entry->my_select->label()` if you wanted.

Just use `$entry->my_select->value() ?? 'Fallback'` or `@if ($entry->my_select->value())`.

It's no different than getting an empty `Illuminate\Support\Collection` and doing `@if ($collection)`. It'll still always be true even if it's empty.
