### ISSUE TITLE
Parent page not saving in YAML or showing in list

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#5938]
### Bug description

Weird one here. The parent page is saving in the tree, but not on the entry.

I can set the parent page of an entry and all appears fine, even after a refresh:

![image](https://user-images.githubusercontent.com/20210934/165766138-532b765c-3e5a-4598-adb4-e0639af432f7.png)

The tree view is fine:

![image](https://user-images.githubusercontent.com/20210934/165767152-9b98e5e4-4de0-4474-a64a-7960f2eff736.png)

But the list view parent is empty:

![image](https://user-images.githubusercontent.com/20210934/165766416-fef12c5c-26b5-4569-8912-b7d33db9c8ff.png)

And when I check the entry's yaml there is no parent listed.

### How to reproduce

Not sure!

### Versions

Statamic 3.3.9 Pro
Laravel 9.10.0
PHP 8.1.1
aerni/livewire-forms 3.2.0
jonassiewertsen/statamic-livewire 2.9.0
rias/statamic-redirect 2.1.2
spatie/statamic-responsive-images 2.11.2
statamic/seo-pro 3.1.0

### Installation

Existing Laravel app

**Comment by duncanmcclean** [comment]
Does it show filled when you edit the entry?

**Comment by jasonvarga** [comment]
The parent shouldn't be in the yaml. It knows about its parent based on its position in the tree.

But it should be shown in the listing. 👍 Valid issue.

**Comment by stuartcusackie** [comment]
@jasonvarga Oh, that's odd for me then because all of my working child entries have something like this in their yaml:
`parent: d7d10536-74b9-427c-bed0-9d0054b0c1df`

Maybe I did something weird with a custom parent field or something.

**Comment by jasonvarga** [comment]
They shouldn't be in there. That's a known issue. https://github.com/statamic/cms/issues/5457 You didn't do anything wrong.

**Comment by duncanmcclean** [comment]
Just tested this on the latest version of Statamic...

It doesn't seem like it's possible to add the "Parent" field as a column in the entries listing table, even if you manually change the "Listable" setting on the field in the blueprint. [I believe](https://github.com/statamic/cms/commit/ed3f0adfca24cbf7b85262b1f2bf1ac609488fec) this behaviour is intentional.

Regarding the `parent` key, as Jason mentioned, it shouldn't get saved to the YAML file since the entry's parent is determined by where that entry sits in the collection's "tree".

If it _is_ being saved to the YAML file, then that's a bug (see #5457).
