### ISSUE TITLE
Revealer hidden data not always saved when replicator sets are collapsed by default

### ISSUE THREAD

**Issue by jesseleite** [statamic/cms#6018]
### Bug description

While we fixed revealer hidden data not saving in #5878, this is still an issue when replicator sets are specifically configured to be collapsed by default...

![image](https://user-images.githubusercontent.com/5187394/167663950-94141974-26dc-4487-a884-ca57b1ef956b.png)

References #5873

### How to reproduce

- Create replicator with a revealer inside your replicator set
- Configure replicator to collapse all sets by default
- Save entry and watch revealer-hidden fields disappear unless fields are revealed in UI

### Versions

Statamic 3.3.10 Pro
Laravel 9.9.0
PHP 8.1.5

**Comment by robdekort** [comment]
I stumbled upon the issue because the `toggle` fieldtype is all of a sudden not saving data anymore. I use it to visually hide fields and at some point this broke:
<img width="818" alt="Screen Shot 2022-05-16 at 09 10 35" src="https://user-images.githubusercontent.com/69107412/168538193-f2a148d6-2d31-4e5a-b96c-4ab5f0b0f6fc.png">

This change means that on all live Peak sites using the button(s) component all the data belonging to button gets trashed upon save when the toggle is off.

So I switched to the revealer fieldtype as a workaround but this shows exactly the same behavior (3.3.11).
