### ISSUE TITLE
uri is not changed after editing the slug

### ISSUE THREAD

**Issue by Oleafeon** [statamic/cms#6069]
### Bug description

I have a website witch has the addon eloquent driver in it, it also has a patch in it off [this](https://github.com/statamic/eloquent-driver/pull/42) pull request, i came acros a problem and i cant find if the problem is in statamic or in the addon

the problem
when i save an entry for the first time the uri is set up good
![image](https://user-images.githubusercontent.com/20043831/169501209-3dcea82a-56db-4ff7-b6b1-5e8efae36d78.png)

But if i change the slug after that the slug will get changed but the uri will stay the same
![image](https://user-images.githubusercontent.com/20043831/169501548-bd5ccd17-a458-4892-9e00-ec8b3aa05bf9.png)

Because of this i get an 404 on the frontend because the uri is not the same as the slug
and the uri's of all the childs are not changed as well

i have asked the [ryanmitchell](https://github.com/ryanmitchell) the person who created the pull request for this addon about it and he said that he could not replicate the problem and it may have been in statamic, i have this problem in multiple sites that use that addon

i have revisions on and its a multisite

### How to reproduce

1. create a page
2. check if the uri is set
3. change the slug of the page
4. uri is not changed

### Versions

Statamic 3.3.12 Pro
Laravel 9.13.0
PHP 8.1.2
aerni/font-awesome 1.2.0
aryehraber/statamic-captcha 1.8.0
doublethreedigital/duplicator 2.2.0
jacksleight/statamic-bard-mutator 1.1.1
rias/statamic-link-it 2.2.3
statamic/eloquent-driver 0.2.0 (with an patch off https://github.com/statamic/eloquent-driver/pull/42)
statamic/seo-pro 3.1.0

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by ryanmitchell** [comment]
To help explain why I think its a core issue rather than in eloquent driver.

When saving we are storing the value of Entry::uri(), which ultimately brings you [to here](https://github.com/statamic/cms/blob/662bc32f0c0de863655ebd1fbc79fbd6b9387348/src/Structures/CollectionStructure.php#L29). 

The value of flattenedPages() is [cached here](https://github.com/statamic/cms/blob/662bc32f0c0de863655ebd1fbc79fbd6b9387348/src/Structures/Tree.php#L117), so would never be getting the new slug to generate the new uri.

**Comment by jackmcdade** [comment]
Closing this as its a bit stale and no one has contributed any info for more than a year. Feel free to reopen if there's any more detail that we could dig into!
