### ISSUE TITLE
Glide manipulating external image

### ISSUE THREAD

**Issue by codedge** [statamic/cms#6105]
### Bug description

When using glide to load an external image, manipulate and serve it, I still get the original image without any changes (width, heigth, quality, etc.) applied.

### How to reproduce

Loading an external image, f. ex. from Instagram API.

Example: `https://scontent-ber1-1.cdninstagram.com/v/t51.29350-15/244716575_194960056047466_7638029823774100705_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=8ae9d6&_nc_ohc=SrkqF0twUlgAX_hLCL9&_nc_ht=scontent-ber1-1.cdninstagram.com&edm=ANo9K5cEAAAA&oh=00_AT-rO70m75BJ45PemLytAp0zC5Dhpr_asbdPKUdKKCTJkA&oe=62962256`

**Glide tag pair**
```html
{{ glide :src="media_url" q="75" w="640" absolute="true" }}
                            <img src="{{ url }}"
                            width="640"
                            height="640"
                            alt="{{ caption | sanitize }}"
                            loading="lazy"
                            />
{{ /glide }}
```

The generated URL is still the old Instagram CDN url.

Even if I remove the `absolute=true` parameter, it will string the host `www.instagram.com/...` and tries to load the image from the local host, which fails.

## Expected result
A local url with the params `https://my.host.com?q=75&w=640` applied that serves the reduced version of the original instagram image.

### Versions

PHP: 8.1
Statamic: 3.3.12

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by jasonvarga** [comment]
Nice find.

Looks like this is because of the query string. Statamic struggles to work out the file extension. 

In your example,

```
https://scontent-ber1-1.cdninstagram.com/v/t51.29350-15/244716575_194960056047466_7638029823774100705_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=8ae9d6&_nc_ohc=SrkqF0twUlgAX_hLCL9&_nc_ht=scontent-ber1-1.cdninstagram.com&edm=ANo9K5cEAAAA&oh=00_AT-rO70m75BJ45PemLytAp0zC5Dhpr_asbdPKUdKKCTJkA&oe=62962256
```

It thinks the file extension is

```
com&edm=ANo9K5cEAAAA&oh=00_AT-rO70m75BJ45PemLytAp0zC5Dhpr_asbdPKUdKKCTJkA&oe=62962256
```

It's a bug.

**Comment by jasonvarga** [comment]
Okay this is a bit of a weird one, but it's a little bit blocked for now.

Even with @ryanmitchell 's PR #6132 which was the initial problem... that just revealed another problem.

Turns out when Glide tries to save the file, it fails because the filename is too long - because the image url is just too long.
It's a PHP/Filesystem limitation. You can't have a directory called `244716575_194960056047466_7638029823774100705_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=8ae9d6&_nc_ohc=SrkqF0twUlgAX_hLCL9&_nc_ht=scontent-ber1-1.cdninstagram.com&edm=ANo9K5cEAAAA&oh=00_AT-rO70m75BJ45PemLytAp0zC5Dhpr_asbdPKUdKKCTJkA&oe=62962256`. It's just too long.

A few things you could try:
- See if you can get a shorter Instagram URL. Maybe they have alternatives in the API?
- Set up your glide cache disk somewhere else, like S3. Maybe they don't have a filename length restriction. I haven't tried.
- Instead of using instagram URLs directly, download the instagram image and put it in one of your own asset containers. Then use Glide on that.
