### ISSUE TITLE
Cross-Origin Headless Live Preview is broken in Statamic 3.3.17

### ISSUE THREAD

**Issue by grischaerbe** [statamic/cms#6277]
### Bug description

[This merged PR](https://github.com/statamic/cms/pull/6206) introduced mechanics to maintain the scroll position on Headless Live Preview across reloads but it fails on Cross-Origin Headless Live Preview. Since there's also no error handling implemented, it not only fails to maintain the scroll position but fails to show new content altogether.

I would strongly suggest leaving features like maintaining the scroll position or updating the content to the frontend and push events via `postMessage`.

### How to reproduce

- Use the Headless Live Preview feature in a cross-origin setup

### Versions

Statamic 3.3.17 Pro
Laravel 8.83.5
PHP 8.1.6

### Installation

Other (please explain)

**Comment by jasonvarga** [comment]
Sorry about that. This should be fixed in #6282.

> I would strongly suggest leaving features like maintaining the scroll position or updating the content to the frontend and push events via postMessage.

This is a good solution but I'd rather it be opt-in. Most people would be using regular live preview pages, so it would be nice for it to "just work" for the majority. For people using headless, there should be a config to swap out this solution for postMessage.
