### ISSUE TITLE
Multiple variables with "modify_date" modifers in same view messes up the dates

### ISSUE THREAD

**Issue by axelferdinand** [statamic/cms#6415]
### Bug description

I just discovered a really, really weird bug.

Try adding 3 or more dates with the `modify_date` modifier:

```
{{ date }}
{{ date modify_date="+1 weeks" }}
{{ date modify_date="+2 weeks" }}
{{ date modify_date="+3 weeks" }}
{{ date modify_date="+4 weeks" }}
{{ date modify_date="+5 weeks" }}
```

This will be the output:

```
30.08.2022
06.09.2022
20.09.2022  <-- Here something goes wrong
11.10.2022   <-- ...the jumps are too big...
08.11.2022  <-- ...and it continues for the following dates!
13.12.2022
```

### How to reproduce

(do the stuff above)

### Logs

```shell
No logs!
```

### Environment

```yaml
Statamic 3.3.24 Pro
Laravel 8.83.21
PHP 8.1.5
aryehraber/statamic-captcha 1.8.0
doublethreedigital/duplicator 2.3.1
jacksleight/statamic-bard-mutator 1.1.1
jacksleight/statamic-bard-texstyle 1.0.3
pecotamic/sitemap 1.4.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
Whats happening is that carbon instances are mutable, so when you modify the date, it sticks.

I think it's fairly easily fixable, but I think it would be a breaking change and would need some more thought.

In the mean time, you can use a custom modifier that clones the carbon instance first. Drop this into `app/Modifiers/Modifydate.php`

```php
<?php

namespace App\Modifiers;

use Statamic\Modifiers\Modifier;
use Statamic\Support\Arr;

class Modifydate extends Modifier
{
    public function index($value, $params, $context)
    {
        return $value->clone()->modify(Arr::get($params, 0));
    }
}
```

Then use `modifydate` instead of `modify_date`.

**Comment by axelferdinand** [comment]
Wow, that was a fast fix!! Thanks @jasonvarga !! The custom modifier works like a charm... Statamic <3
