### ISSUE TITLE
Assets: Uploading multiple assets results in "Asset already exists" error

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#838]
"Asset already exists" error when uploading multiple files to empty folder. 

<img width="1513" alt="Screen Shot 2019-10-24 at 11 15 01 am" src="https://user-images.githubusercontent.com/414211/67532351-a4a08a00-f711-11e9-935e-d04f20ad6d18.png">

**Comment by danielmorgan** [comment]
Just came across what appears to be the same issue. It prevented the other uploaded files from appearing in the control panel assets view.

![image](https://user-images.githubusercontent.com/530996/72629741-cee89900-3948-11ea-81b1-f0074267b62c.png)

On inspecting the upload directory I noticed a 0 byte file, and removing it resolved the issue.

![image](https://user-images.githubusercontent.com/530996/72629682-b5dfe800-3948-11ea-8700-7a2f66250f64.png)

I can recreate it consistently by trying to upload this file. In a production environment the progress bar appears to work as normal. In a local environment it fails instantly and returns "getimagesize(): Read error!".

[funeral.jpg](https://user-images.githubusercontent.com/530996/72630188-bd53c100-3949-11ea-9c66-e2aac0ef4830.jpg)

**Comment by zawilliams** [comment]
I found this to be happening with DigitalOcean Spaces as well. We are switching to S3 though because we also were having 503s and connection issues.

@danielmorgan were you getting the "getimagesize(): Read error!" with just the local filesystem or were you uploading to S3 or another service?

**Comment by zawilliams** [comment]
Just did a test locally instead of on S3 just to check and can confirm that when there is a 0 byte file in a folder that you are navigating to, it will give the "File already exists at path: ..." error via the `League\Flysystem\FileExistsException`.

If you load a folder within your Assets that has a 0 byte file, it will say "This container is empty".

But yes, removing the 0 byte file will fix the issue. I believe I had a couple of failed uploads that caused the 0 byte files.
