### ISSUE TITLE
Validation rule "digits between" does not actually validate

### ISSUE THREAD

**Issue by rubzie** [statamic/cms#8767]
### Bug description

I used [this validation](https://laravel.com/docs/10.x/validation#rule-digits-between) in my form field, but the field does not actually give an error if a value outside the specified range is entered.

### How to reproduce

1. Create a form
2. edit its blueprint
3. add an integer field
4. add the Validation rule `digits_between:1,10000` ([screenshot of that](https://i.ruben.org/211D5G6l))
5. Save blueprint and form
6. Use the form, enter the number 0 or 342567 in the form
7. Submit the form, no validation error is returned

### Environment

```yaml
Statamic 4.23.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by jasonvarga** [comment]
The `digits_between` rule validates the _length_ of the number.

e.g. If you do `digits_between:2,4`
- 0-9 is invalid because its a single digit
- 10-9999 are valid because 10 is 2 digits and 9999 is 4 digits.
- 10000+ is invalid because its more than 4 digits.

I think you're looking for a combination of the `integer` and `between:1,10000` rules.

```yml
validate:
  - 'integer'
  - 'between:1,10000'
```

**Comment by rubzie** [comment]
Aww damn, thanks for educating me @jasonvarga :o

**Comment by jasonvarga** [comment]
![](https://media.giphy.com/media/3ov9k01Y5IKizNmC7S/giphy-downsized.gif)
