### ISSUE TITLE
Save as html bard field set revision as dirty on save.

### ISSUE THREAD

**Issue by Bernier154** [statamic/cms#9068]
### Bug description

When i set the option "save as html" in a bard field. The collection is unpublishable, It saves, then process the bard field, as it process it, it set the revision as dirty and prevent publishing.

https://github.com/statamic/cms/assets/31347745/45654ec9-fb86-4ff3-ac89-b8a8d6de52a1

### How to reproduce

Minimum to reproduce is:
New collection with revision enabled + a bard field that save as html.

### Logs

```shell
There are no relevant logs it's a frontend bug and nothing in the console.
```

### Environment

```yaml
PHP 8.2.12
Statamic 4.36.0
Laravel 10.10

Firefox and chrome
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by naabster** [comment]
We have the same Problem. After saving you need to reload the page (Browser refresh) to be able to publish the entry.

**Comment by K3CK** [comment]
We have the same problem after upgrading to the latest version of Statamic in one of our projects. And I can confirm that downgrading to 4.34.0 fixes the problem. 

It's notable that in our case the triggering of the dirty state happens although we don't save it as HTML. 

Likewise the problem seems to occur only in special cases. We have some projects where it doesn't occur. We could not yet find out why this is the case.

**Comment by K3CK** [comment]
@vluijkx Yes, you are right, saving the revisions with the eloquent-driver is the thing what makes the difference in our projects. When saving the revisions as file it works, saving in the database with eloquent it does not work.

**Comment by naabster** [comment]
We do not store revisions in database, we only store users with eloquent in database.
