### ISSUE TITLE
Ability to add external css and js assets

### ISSUE THREAD

**Issue by suabahasa** [statamic/cms#961]
ability to add external css and js on control panel. 
the current static function Statamic::script always looking to vendor folder

**Comment by jasonvarga** [comment]
Not sure what you’re asking for.

**Comment by jackmcdade** [comment]
Maybe this is what you're looking for? <https://statamic.dev/extending/control-panel#adding-css-and-js-assets>

**Comment by suabahasa** [comment]
https://statamic.dev/extending/control-panel#adding-css-and-js-assets

i mean, the function for adding css and js assets to control panel should not strict to local assets.
maybe with optional parameter, we can choose between local assets or external assets

**Comment by suabahasa** [comment]
example, 
public static function Statamic::js(string path, string vendor, bool external){}

**Comment by jasonvarga** [comment]
I have no problem adding a way to do this but I’m curious why you want to do it.

**Comment by jackmcdade** [comment]
Just throwing my 2 cents in here, we strongly recommend that whenever possible that addons be written so that the Statamic control panel will work when offline. I do realize that there are a few cases where this isn't possible, like using a Google API for geocoding, but do try to avoid using CDNs for jQuery and that kind of thing. That's what `npm` is for :)

**Comment by jasonvarga** [comment]
Google Maps is a good example.

My only question would be that potentially multiple addons would want to insert the same external script. Maybe that's not even an issue.

**Comment by jackmcdade** [comment]
Ah yes, that _is_ a good example. I stand corrected!
