### ISSUE TITLE
Translator issues

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#972]
1) ```php translator generate``` does not generate the string "Groups" in the .json file (currently: de.json, es.json, fr.json)
"Groups" is included in the main sidebar of the cp

2) ```php translator translate``` (using Google Cloud translation API) has some caveats:
English strings that include variable placeholders (such as :count) are either:
-  badly translated (:count is translated)
-  untranslated (:count is kept as such which is what we would like)
-  even deleted (:count is deleted from the string)

As an exemple: in validation.php, the :attribute string has been deleted from all translated files though it is visible in the English validation.php file.

3) Most if not all translated messages are not displayed when viewing the cp in another language. We get ```statamic::key_of_message``` instead of the intended translation.

**Comment by jasonvarga** [comment]
Where do you see the `:count` or `:attribute` strings within the translation files?

**Comment by ebeauchamps** [comment]
:attribute is in validation.php (English file) in my base install => Laravel file?
:attribute <em>isn't</em> in validation.php (English file) in statamic/cms/resources/lang/en

That's confusing.
As confusing as having other Laravel files in English on the base install but not in statamic/cms

**Comment by jasonvarga** [comment]
Statamic uses its own validation file when inside the control panel. (eg. it loads the key `statamic::validation.required` rather than simply `validation.required`) We do this so we can use grammar suitable for inline errors like "This field is required" instead of "The :attribute field is required".

The `validation.php` found in your base install will be used outside of the CP.

All the Statamic translations live in the `statamic/cms` repo, which means once you install Statamic, they can be found in `vendor/statamic/cms/resources/lang`.

If you want to customize the Statamic translations quicky (eg. for testing something) you can edit the files in the `vendor` directory. However since editing files in `vendor` is not a great practice, you can override them the real way, by placing new files in `resources/lang/vendor/statamic/fr/`.

I will put this information in the docs.
