### ISSUE TITLE
"inline_label_when_true" missing from toggle form view

### ISSUE THREAD

**Issue by jolora** [statamic/cms#9776]
### Bug description

There is no output for "inline_label_when_true" in the default view for toggles: `resources/views/extend/forms/fields/toggle.antlers.html`

I've not got time to create and test a pull request but something like 

```
{{ if inline_label_when_true && (value && value !== '0') }}
  {{ inline_label_when_true }}
{{ elseif inline_label }}
  {{ inline_label }}
{{ /if }}
```

should do it I think.

### How to reproduce

Add an "inline_when_true" value to a toggl field in a form blueprint and you'll find it makes no appearane on the frontend.

### Environment

```yaml
Statamic Version: 4.54.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by duncanmcclean** [comment]
Thanks for opening this issue.

When this setting is used in the Control Panel, we display the different inline label immediately after the toggle is toggled, like this:

![CleanShot 2024-03-26 at 15 28 17](https://github.com/statamic/cms/assets/19637309/b667275e-4805-4649-9933-37181bff5dee)

The code snippet you suggested would only work after an initial submission (eg. if you got validation errors) and it wouldn't update after changing the state of the toggle. In order to replicate the behaviour of the setting in the Control Panel, you'd need to know the state of the toggle. 

However, since our form logic is decoupled from your front-end stack (eg. Alpine / Vue / jQuery / etc), it'd need to be something you'd implement yourself by [publishing the [form field views](https://statamic.dev/tags/form-create#prerendered-field-html)].

For example, if you're using Alpine.js, you could do something like this:

```antlers
<label>
    <input type="hidden" name="{{ handle }}" value="0">
    <input
        type="checkbox"
        name="{{ handle }}"
        value="1"
        {{ if js_driver }}{{ js_attributes }}{{ /if }}
        {{ if value && value !== '0' }}checked{{ /if }}
        {{ if validate|contains:required }}required{{ /if }}
    >
    {{ if inline_label && inline_label_when_true }}
        <span x-text="form.{{ handle }} == true ? '{{ inline_label_when_true }}' : '{{ inline_label }}'"></span>
    {{ elseif inline_label }}
        {{ inline_label }}
    {{ /if }}
</label>
```

_^ note: this code might need some tweaking, I haven't tested it_

**Comment by jolora** [comment]
Thanks for the response @duncanmcclean -- I've done similar on my frontend. Makes sense now you remind me that the default form field views are de-coupled from the frontend stack. Maybe it would be nice to have a couple of alternative vendor views (one for Alpine, one for Vue etc) that would handle the vast majority of stacks?
