### ISSUE TITLE
What should site:clear remove?

### ISSUE THREAD

**Issue by vladdu** [statamic/cms#981]
When running site:clear, not everything is removed: the public/assets folder is left behind, and also the css and js files. Is that as designed? Shouldn't everything be cleared?

**Comment by jesseleite** [comment]
The purpose of `site:clear` is to clear anything relating to content or config in a Statamic app.  Both Statamic and Laravel are pretty hands off around css/js/frontend stuff though.  I'm not sure if `site:clear` should touch anything in the frontend build pipeline, due to how opinionated that stuff is.  Nothing is set in stone right now though ☺️

As for that `public/assets`, we remove the asset container filesystem, so we should probably remove that folder as well.  Good find, thanks!

**Comment by steveooo1** [comment]
Maybe the question is: Should Statamic start with `site:clear` per default, so you start with a clean slate and build from up there?

**Comment by jasonvarga** [comment]
We ship `statamic/statamic` at a thoughtful starting point for most users.

Most of the time you'll want a homepage and an asset container. If we started everyone from a completely blank slate you would need to do these boilerplate setup tasks every time.

**Comment by vladdu** [comment]
I'm okay with the explanations and clearing the assets. Thanks!

**Comment by jesseleite** [comment]
Probably 80%+ ([source analytics](https://youtu.be/dQw4w9WgXcQ)) of people use pages and assets, not to mention people are used to having these things setup out-of-the-box in v2.  This setup makes the transition to v3 smoother for most people.  The rest of you can `site:clear` if you want a truly blank slate without pages, assets, etc 👌

**Comment by steveooo1** [comment]
Okay, well. You guys are right. Its' okay right now and good points! The neurotic minimalist was taking over... Peace! :)

**Comment by jesseleite** [comment]
The best kind of neurotic!
