### ISSUE TITLE
Error when creating a collection

### ISSUE THREAD

**Issue by aerni** [statamic/cms#990]
Creating a collection is impossible and results in this error: `The given data was invalid.`

**How to reproduce**
1. Create a new collection in the CP
2. Leave everything at its default but change the default status to `draft`
3. Finish the process and get error

I can't quite figure out a pattern here. Creating a collection works with some configurations and with others it doesn't.

**Comment by psren** [comment]
I second that :-)

Here a more info.
![image](https://user-images.githubusercontent.com/1016798/69656743-5fa5a580-1079-11ea-912b-2b96748341fc.png)

The error in the developer console is:

```js
{"message":"The given data was invalid.","errors":{"default_publish_state":["Must be true or false."]}}
```

In the Vue-Devtools the `default_publish_state` is `"true"` or `"false"`.
It seems to be a `string` vs `bool` issue.

If I change the value in the Vue-Devtools to a `boolean` everything seems to work as expected.
Also this seems to be a regression since i already have some collections ;-)
